/* 자동 생성 — tools/gen_antd_demos.py. 손으로 고치지 말 것.
 *
 * ⚠️ 전부 미리 싣지 않는다. 예제 모듈 하나가 antd 컴포넌트 십수 종을 끌고 오므로,
 *    한 화면을 보는 사람이 72종의 무게를 지면 안 된다. 동적 import 로 늦게 부른다.
 */
import type { DemoModule } from "./types";

export type { DemoProps, DemoSet, ToneColor, DemoModule } from "./types";

const LOADERS: Record<string, () => Promise<DemoModule>> = {
  "affix": () => import("./affix").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "alert": () => import("./alert").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "anchor": () => import("./anchor").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "app": () => import("./app").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "auto-complete": () => import("./auto-complete").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "avatar": () => import("./avatar").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "badge": () => import("./badge").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "border-beam": () => import("./border-beam").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "breadcrumb": () => import("./breadcrumb").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "button": () => import("./button").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "calendar": () => import("./calendar").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "card": () => import("./card").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "carousel": () => import("./carousel").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "cascader": () => import("./cascader").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "checkbox": () => import("./checkbox").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "collapse": () => import("./collapse").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "color-picker": () => import("./color-picker").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "config-provider": () => import("./config-provider").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "date-picker": () => import("./date-picker").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "descriptions": () => import("./descriptions").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "divider": () => import("./divider").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "drawer": () => import("./drawer").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "dropdown": () => import("./dropdown").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "empty": () => import("./empty").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "flex": () => import("./flex").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "float-button": () => import("./float-button").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "form": () => import("./form").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "grid": () => import("./grid").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "icon": () => import("./icon").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "image": () => import("./image").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "input-number": () => import("./input-number").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "input": () => import("./input").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "layout": () => import("./layout").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "list": () => import("./list").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "listy": () => import("./listy").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "masonry": () => import("./masonry").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "mentions": () => import("./mentions").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "menu": () => import("./menu").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "message": () => import("./message").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "modal": () => import("./modal").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "notification": () => import("./notification").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "pagination": () => import("./pagination").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "popconfirm": () => import("./popconfirm").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "popover": () => import("./popover").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "progress": () => import("./progress").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "qr-code": () => import("./qr-code").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "radio": () => import("./radio").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "rate": () => import("./rate").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "result": () => import("./result").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "segmented": () => import("./segmented").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "select": () => import("./select").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "skeleton": () => import("./skeleton").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "slider": () => import("./slider").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "space": () => import("./space").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "spin": () => import("./spin").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "splitter": () => import("./splitter").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "statistic": () => import("./statistic").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "steps": () => import("./steps").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "switch": () => import("./switch").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "table": () => import("./table").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "tabs": () => import("./tabs").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "tag": () => import("./tag").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "time-picker": () => import("./time-picker").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "timeline": () => import("./timeline").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "tooltip": () => import("./tooltip").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "tour": () => import("./tour").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "transfer": () => import("./transfer").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "tree-select": () => import("./tree-select").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "tree": () => import("./tree").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "typography": () => import("./typography").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "upload": () => import("./upload").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
  "watermark": () => import("./watermark").then((m) => ({ demos: m.DEMOS, skipped: m.SKIPPED })),
};

/** 못 세우는 슬러그면 `null` — 빈 객체를 주지 않는다. 둘은 다른 뜻이다. */
export function loadDemos(slug: string): Promise<DemoModule> | null {
  const load = LOADERS[slug];
  return load ? load() : null;
}
