// @ts-nocheck
/* 자동 생성 — tools/gen_fluent_demos.py. 손으로 고치지 말 것. 스토리 모듈은 공식 index.stories.tsx·스토리 파일 바이트 그대로이고 첫 줄 `// @ts-nocheck` 만 더했다(모듈 경계 (a)). */
import { composeStory } from "../../storybookCompose";
export const demos = {
};
export const skipped = {
  "Default": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "TextInput": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "FirstDayOfTheWeek": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "WeekNumbers": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "DateRange": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "DateBoundaries": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "CustomDateFormatting": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "Localized": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "ErrorHandling": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "Controlled": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "Required": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
  "Disabled": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-calendar-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx) · @fluentui/react-datepicker-compat (packages/react-components/react-datepicker-compat/stories/src/DatePicker/index.stories.tsx)"},
};
