// @ts-nocheck
/* 자동 생성 — tools/gen_fluent_demos.py. 손으로 고치지 말 것. 스토리 모듈은 공식 index.stories.tsx·스토리 파일 바이트 그대로이고 첫 줄 `// @ts-nocheck` 만 더했다(모듈 경계 (a)). */
import { composeStory } from "../../storybookCompose";
export const demos = {
};
export const skipped = {
  "Default": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-datepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/TimePickerWithDatePicker.stories.tsx) · @fluentui/react-timepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/index.stories.tsx)"},
  "Controlled": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-datepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/TimePickerWithDatePicker.stories.tsx) · @fluentui/react-timepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/index.stories.tsx)"},
  "Clearable": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-datepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/TimePickerWithDatePicker.stories.tsx) · @fluentui/react-timepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/index.stories.tsx)"},
  "FreeformWithErrorHandling": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-datepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/TimePickerWithDatePicker.stories.tsx) · @fluentui/react-timepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/index.stories.tsx)"},
  "FreeformCustomParsing": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-datepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/TimePickerWithDatePicker.stories.tsx) · @fluentui/react-timepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/index.stories.tsx)"},
  "TimePickerWithDatePicker": {"code": "package-missing", "detail": "이 컴포넌트의 공식 index.stories.tsx 가 함께 부르는 파일이 미설치 패키지를 불러요 — @fluentui/react-datepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/TimePickerWithDatePicker.stories.tsx) · @fluentui/react-timepicker-compat (packages/react-components/react-timepicker-compat/stories/src/TimePicker/index.stories.tsx)"},
};
