/* 자동 생성 — tools/gen_heroui_demos.py. 손으로 고치지 말 것.
 *
 * ⚠️ 경로를 템플릿(`import(`./${slug}`)`)으로 만들지 않는다 — 번들러가 폴더 전체를
 *    끌어와 안 쓰는 파일까지 빌드에 넣는다. 슬러그마다 명시한 import 함수로 둔다.
 */
const LOADERS: Record<string, () => Promise<unknown>> = {
  "accordion": () => import("./accordion/index"),
  "alert": () => import("./alert/index"),
  "alert-dialog": () => import("./alert-dialog/index"),
  "autocomplete": () => import("./autocomplete/index"),
  "avatar": () => import("./avatar/index"),
  "badge": () => import("./badge/index"),
  "breadcrumbs": () => import("./breadcrumbs/index"),
  "button": () => import("./button/index"),
  "button-group": () => import("./button-group/index"),
  "calendar": () => import("./calendar/index"),
  "card": () => import("./card/index"),
  "checkbox": () => import("./checkbox/index"),
  "checkbox-group": () => import("./checkbox-group/index"),
  "chip": () => import("./chip/index"),
  "close-button": () => import("./close-button/index"),
  "color-area": () => import("./color-area/index"),
  "color-field": () => import("./color-field/index"),
  "color-picker": () => import("./color-picker/index"),
  "color-slider": () => import("./color-slider/index"),
  "color-swatch": () => import("./color-swatch/index"),
  "color-swatch-picker": () => import("./color-swatch-picker/index"),
  "combo-box": () => import("./combo-box/index"),
  "date-field": () => import("./date-field/index"),
  "date-picker": () => import("./date-picker/index"),
  "date-range-picker": () => import("./date-range-picker/index"),
  "description": () => import("./description/index"),
  "disclosure": () => import("./disclosure/index"),
  "disclosure-group": () => import("./disclosure-group/index"),
  "drawer": () => import("./drawer/index"),
  "dropdown": () => import("./dropdown/index"),
  "error-message": () => import("./error-message/index"),
  "field-error": () => import("./field-error/index"),
  "fieldset": () => import("./fieldset/index"),
  "form": () => import("./form/index"),
  "input": () => import("./input/index"),
  "input-group": () => import("./input-group/index"),
  "input-otp": () => import("./input-otp/index"),
  "kbd": () => import("./kbd/index"),
  "label": () => import("./label/index"),
  "link": () => import("./link/index"),
  "list-box": () => import("./list-box/index"),
  "meter": () => import("./meter/index"),
  "modal": () => import("./modal/index"),
  "number-field": () => import("./number-field/index"),
  "pagination": () => import("./pagination/index"),
  "popover": () => import("./popover/index"),
  "progress-bar": () => import("./progress-bar/index"),
  "progress-circle": () => import("./progress-circle/index"),
  "radio-group": () => import("./radio-group/index"),
  "range-calendar": () => import("./range-calendar/index"),
  "scroll-shadow": () => import("./scroll-shadow/index"),
  "search-field": () => import("./search-field/index"),
  "select": () => import("./select/index"),
  "separator": () => import("./separator/index"),
  "skeleton": () => import("./skeleton/index"),
  "slider": () => import("./slider/index"),
  "spinner": () => import("./spinner/index"),
  "surface": () => import("./surface/index"),
  "switch": () => import("./switch/index"),
  "table": () => import("./table/index"),
  "tabs": () => import("./tabs/index"),
  "tag-group": () => import("./tag-group/index"),
  "text-area": () => import("./text-area/index"),
  "text-field": () => import("./text-field/index"),
  "time-field": () => import("./time-field/index"),
  "toast": () => import("./toast/index"),
  "toggle-button": () => import("./toggle-button/index"),
  "toggle-button-group": () => import("./toggle-button-group/index"),
  "toolbar": () => import("./toolbar/index"),
  "tooltip": () => import("./tooltip/index"),
  "typography": () => import("./typography/index"),
};

/** 이 베이스 슬러그가 아니면 `null`. 빈 객체를 주지 않는다 — 둘은 다른 뜻이다. */
export function loadDemos(slug: string) {
  const load = LOADERS[slug];
  return load ? load() : null;
}
