// @ts-nocheck
/* 자동 생성 — tools/gen_primer_demos.mjs. 손으로 고치지 말 것. 스토리 모듈은 공식 스토리 파일의 최상위 선언 바이트 그대로(⑤ import 치환만). */
import { composeStory } from "../../storybookCompose";
export const demos = {
};
export const skipped = {
  "Default": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "SimpleList": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithVisualListHeading": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithCustomHeading": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithIcons": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithAvatars": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "ItemDividers": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "SingleDivider": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "InlineDescription": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "BlockDescription": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "SingleSelect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "InactiveSingleSelect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "MultiSelect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "ListboxSingleSelect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "ListboxMultiSelect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithDynamicContent": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "DisabledSelectedMultiselect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "DisabledMultiselect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "InactiveMultiselect": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "DisabledItem": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "InactiveItem": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "LoadingItem": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "Links": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "CustomItemChildren": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "TextWrapAndTruncation": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "ConditionalChildren": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "ChildWithSideEffects": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "InsideOverlay": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "GroupWithSubtleTitle": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "GroupWithFilledTitle": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithCustomTrailingVisuals": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithKeyboardShortcuts": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithTrailingCount": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithTrailingAction": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "WithTrailingActionOnGroupHeading": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "FullVariant": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
  "LargeItem": {"code":"private-api","detail":"Item — 공개 진입점에는 @primer/react 의 ActionList 멤버로만 있음(import 문으로 못 받음)"},
};
