/* 자동 생성 — tools/gen_blueprint_demos.py. 손으로 고치지 말 것. 예제 모듈을 부르지 않는다(문서 칸만). */
export const DOC_SOURCE = "palantir/blueprint@@blueprintjs/core@6.18.0:packages/core/src/components/button/buttons.mdx";
export const EXAMPLES = [
  {
    "key": "ButtonBasicExample",
    "name": "Basic",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonBasic.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonIntentExample",
    "name": "Intent",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonIntent.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonVariantExample",
    "name": "Variant",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonVariant.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonMinimalExample",
    "name": "Minimal",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonMinimal.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonOutlinedExample",
    "name": "Outlined",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonOutlined.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonSizeExample",
    "name": "Size",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonSize.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonFillExample",
    "name": "Fill",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonFill.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonAlignTextExample",
    "name": "Aligned text",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonAlignText.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonEllipsizeTextExample",
    "name": "Ellipsized text",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonEllipsizeText.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonIconWithTextExample",
    "name": "Icons with text",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonIconWithText.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonIconExample",
    "name": "Icon buttons",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonIcon.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonStatesExample",
    "name": "Button states",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonStates.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonAnchorButtonExample",
    "name": "AnchorButton",
    "axis": "AnchorButton",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonAnchorButton.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonDisabledButtonTooltipExample",
    "name": "AnchorButton",
    "axis": "AnchorButton",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button/ButtonDisabledButtonTooltip.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonPlaygroundExample",
    "name": "Interactive Playground",
    "axis": "Interactive Playground",
    "kind": "playground",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/buttonPlaygroundExample.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  }
];
export const MASTER = {"rule": "doc-order-first", "key": "ButtonBasicExample", "reason": null};
