export function componentGroups(varsCss: string): Set<string> {
  const out = new Set<string>;
  for (const m of varsCss.matchAll(/--component-([a-z0-9]+)-/g)) out.add(m[1]);
  return out;
}

const norm = (s: string) => s.toLowerCase.replace(/[^a-z0-9]/g, "");

const ALIAS: Record<string, string> = {
  // 입력 계열
  autocomplete: "combobox",
  searchautocomplete: "combobox",
  cascadeselect: "select",
  nativeselect: "nativeselect",
  htmlselect: "nativeselect",
  multiselect: "select",
  tagsinput: "inputgroup",
  pininput: "inputotp",
  otpfield: "inputotp",
  numberfield: "input",
  numberinput: "input",
  numericinput: "input",
  passwordinput: "input",
  textinput: "input",
  textarea: "input",
  textfield: "input",
  fileinput: "input",
  filedropzone: "input",
  fileuploader: "input",
  colorinput: "colorpicker",
  colorswatch: "colorpicker",
  swatchpicker: "colorpicker",
  colorarea: "colorpicker",
  colorfield: "colorpicker",
  colorslider: "colorpicker",
  colorwheel: "colorpicker",
  // 그룹형은 개별 토큰 사용
  radiogroup: "radio",
  radiobutton: "radio",
  radiobuttongroup: "radio",
  radiotile: "radio",
  checkboxgroup: "checkbox",
  inlinecheckbox: "checkbox",
  togglegroup: "toggle",
  togglebutton: "toggle",
  buttongroup: "button",
  buttonset: "button",
  compoundbutton: "button",
  splitbutton: "button",
  menubutton: "button",
  iconbutton: "button",
  closebutton: "button",
  copybutton: "button",
  chatbutton: "button",
  floatbutton: "button",
  floatingactionbutton: "button",
  unstyledbutton: "button",
  actionicon: "button",
  actiongroup: "button",
  speeddial: "button",
  // 메뉴 종류
  dropdown: "menu",
  dropdownmenu: "menu",
  overflowmenu: "menu",
  actionmenu: "menu",
  menuitem: "menu",
  megamenu: "navigationmenu",
  navbar: "navigationmenu",
  navlink: "navigationmenu",
  topnavigation: "navigationmenu",
  sidenavigation: "sidebar",
  anchornavigation: "navigationmenu",
  subnav: "navigationmenu",
  tabnav: "tabs",
  breadcrumbs: "breadcrumb",
  // 겹침 또는 띄움 배치
  layer: "dialog",
  modal: "dialog",
  alertdialog: "alertdialog",
  confirmdialog: "alertdialog",
  overlay: "dialog",
  overlay2: "dialog",
  previewcard: "hovercard",
  contextmenupopover: "contextmenu",
  popovernext: "popover",
  // 알림, 표시
  callout: "alert",
  inlinenotification: "alert",
  notification: "toast",
  toastnotification: "toast",
  messages: "message",
  flash: "alert",
  inlinemessage: "message",
  statusindicator: "badge",
  badgeindicator: "badge",
  counterbadge: "badge",
  presencebadge: "badge",
  circlebadge: "badge",
  tag: "chip",
  compoundtag: "chip",
  taginput: "inputgroup",
  pill: "chip",
  pillsinput: "inputgroup",
  label: "label",
  issuelabel: "label",
  // 진행, 상태
  progressbar: "progress",
  ringprogress: "progress",
  semicircleprogress: "progress",
  loadingoverlay: "spinner",
  inlineloading: "spinner",
  loader: "spinner",
  skeletontext: "skeleton",
  skeletonicon: "skeleton",
  skeletonplaceholder: "skeleton",
  datatableskeleton: "skeleton",
  aiskeleton: "skeleton",
  // 표, 목록
  htmltable: "table",
  datatable: "datatable",
  datagrid: "datatable",
  treegrid: "datatable",
  listview: "listrow",
  listbox: "listrow",
  containedlist: "listrow",
  listgroup: "listrow",
  listitem: "listrow",
  cardlist: "card",
  actioncard: "card",
  itemcard: "card",
  controlcard: "card",
  productcard: "card",
  // 날짜
  datepickerinput: "datepicker",
  fluiddatepickerinput: "datepicker",
  daterangepicker: "datepicker",
  dateinput: "datepicker",
  datefield: "datepicker",
  daterangefield: "datepicker",
  timepicker: "datepicker",
  timefield: "datepicker",
  timeinput: "datepicker",
  rangecalendar: "calendar",
  // 기타
  accordionitem: "accordion",
  disclosure: "collapsible",
  collapse: "collapsible",
  spoiler: "collapsible",
  expandablesection: "collapsible",
  segmentedcontrol: "segmented",
  splitpanel: "resizable",
  panelresizehandle: "resizable",
  scrollpanel: "scrollarea",
  virtualscroller: "scrollarea",
  carouselnav: "carousel",
  galleria: "carousel",
  slideshow: "carousel",
  rating: "meter",
  starrating: "meter",
  thumbsrating: "meter",
  gauge: "meter",
  knob: "slider",
  rangeinput: "slider",
  rangeslider: "slider",
  angleslider: "slider",
  typography: "prose",
  typographystylesprovider: "prose",
  richtexteditor: "prose",
  editor: "prose",
  markdown: "prose",
  text: "prose",
  title: "prose",
  heading: "prose",
  blockquote: "prose",
  code: "kbd",
  codeblock: "kbd",
  codeview: "kbd",
  keybindinghint: "kbd",
  keyboard: "kbd",
  statistic: "stat",
  bignumber: "stat",
  numberformatter: "stat",
  wizard: "stepper",
  steplist: "stepper",
  steps: "stepper",
  progressindicator: "stepper",
  pagehead: "pageheader",
  header: "pageheader",
  contentlayout: "pageheader",
  treeview: "listrow",
  tree: "listrow",
  toolbar: "toolbar",
  splitter: "resizable",
  divider: "divider",
  separator: "divider",
  avatargroup: "avatar",
  userprofile: "avatar",
  cascader: "select",
  treeselect: "select",
  selectitem: "select",
  selectitemgroup: "select",
  inputnumber: "input",
  mentions: "combobox",
  upload: "input",
  fileupload: "input",
  rate: "meter",
  anchor: "link",
  list: "listrow",
  simplelist: "listrow",
  timeline: "stages",
  activitytimeline: "stages",
  panelstack: "stages",
  image: "aspectratio",
  backgroundimage: "aspectratio",
  aspectratiobox: "aspectratio",

  // 폼. field는 래퍼, 도움말, 검증 담당이고 input은 입력 요소 자체
  form: "field",
  forms: "field",
  fieldset: "field",
  formgroup: "field",
  formitem: "field",
  formfield: "field",
  formelement: "field",
  formtext: "field",
  fluidform: "field",
  validation: "field",
  validator: "field",
  errormessage: "field",
  fielderror: "field",
  attributeeditor: "field",
  formcontrol: "input",
  formlabel: "label",
  infolabel: "label",
  floatlabel: "label",
  floatinglabel: "label",
  floatinglabels: "label",
  // 입력 필드
  editabletext: "input",
  editable: "input",
  inplace: "input",
  inputtext: "input",
  inputtextarea: "input",
  inputmask: "input",
  keyfilter: "input",
  password: "input",
  jsoninput: "input",
  filebutton: "input",
  fileselector: "input",
  dropzone: "input",
  filetrigger: "input",
  maskedinput: "input",
  textareaautosize: "input",
  searchfield: "input",
  searchbox: "input",
  spinbutton: "input",
  textfilter: "input",
  promptinput: "input",
  filteredsearch: "input",
  expandablesearch: "input",
  fluidnumberinput: "input",
  fluidsearch: "input",
  fluidtextarea: "input",
  fluidtextinput: "input",
  controlgroup: "inputgroup",
  iconfield: "inputgroup",
  textinputwithtokens: "inputgroup",
  otp: "inputotp",
  range: "slider",
  rangeselector: "slider",
  // 고르개
  picker: "select",
  picklist: "select",
  selectmultiple: "select",
  selectpanel: "select",
  selectpanelv2: "select",
  fluiddropdown: "select",
  fluidmultiselect: "select",
  fluidselect: "select",
  timepickerselect: "select",
  autosuggest: "combobox",
  tagpicker: "combobox",
  mention: "combobox",
  lookups: "combobox",
  propertyfilter: "combobox",
  fluidcombobox: "combobox",
  // 켜고 끄기
  checksradios: "checkbox",
  checkboxbutton: "checkbox",
  checkboxbuttongroup: "checkbox",
  checkboxcard: "checkbox",
  checkmark: "checkbox",
  multistatecheckbox: "checkbox",
  tristatecheckbox: "checkbox",
  checkboxshim: "checkbox",
  radiocard: "radio",
  radiomark: "radio",
  visualpicker: "radio",
  checkboxtoggle: "switch",
  toggleswitch: "switch",
  togglesmall: "switch",
  inputswitch: "switch",
  // 날짜
  datetimepicker: "datepicker",
  datetimeinput: "datepicker",
  fluiddatepicker: "datepicker",
  fluidtimepicker: "datepicker",
  colorswatchpicker: "colorpicker",
  actionbutton: "button",
  logicbutton: "button",
  combobutton: "button",
  dangerbutton: "button",
  primarybutton: "button",
  secondarybutton: "button",
  buttonicons: "button",
  burger: "button",
  fab: "button",
  copy: "button",
  copytoclipboard: "button",
  clipboard: "button",
  downloadtrigger: "button",
  scrolltop: "button",
  // fluent v8에서 v9로 연결하는 shim, v9 버튼 그대로 사용
  actionbuttonshim: "button",
  commandbuttonshim: "button",
  compoundbuttonshim: "button",
  defaultbuttonshim: "button",
  menubuttonshim: "button",
  primarybuttonshim: "button",
  togglebuttonshim: "button",
  // 덮개
  popconfirm: "popover",
  anchoredoverlay: "popover",
  floatingpanel: "popover",
  contextualhelp: "popover",
  teachingpopover: "popover",
  confirmpopup: "popover",
  overlaypanel: "popover",
  popper: "popover",
  drop: "popover",
  toggletip: "tooltip",
  tip: "tooltip",
  composedmodal: "dialog",
  modalwrapper: "dialog",
  dialogcontainer: "dialog",
  dialogtrigger: "dialog",
  prompt: "dialog",
  collectionpreferences: "dialog",
  confirmationdialog: "alertdialog",
  // 차림표, 길잡이
  actionlist: "menu",
  dynamicmenu: "menu",
  menulist: "menu",
  menutrigger: "menu",
  overflowmenuitem: "menu",
  overflowmenuv2: "menu",
  buttondropdown: "menu",
  dropbutton: "menu",
  panelmenu: "menu",
  tieredmenu: "menu",
  navlist: "navigationmenu",
  nav: "navigationmenu",
  globalnavigation: "navigationmenu",
  verticalnavigation: "navigationmenu",
  bottomnavigation: "navigationmenu",
  tableofcontents: "navigationmenu",
  tab: "tabs",
  tabcontent: "tabs",
  tabview: "tabs",
  tabmenu: "tabs",
  scopedtabs: "tabs",
  verticaltabs: "tabs",
  underlinenav: "tabs",
  underlinepanels: "tabs",
  legacyunderlinenav: "tabs",
  navs: "tabs",
  actionbar: "toolbar",
  appbar: "toolbar",
  dock: "toolbar",
  breadcrumbgroup: "breadcrumb",
  breadcrumbitem: "breadcrumb",
  paginationnav: "pagination",
  paginator: "pagination",
  contentswitcher: "segmented",
  togglebuttongroup: "segmented",
  selectbutton: "segmented",
  filter: "segmented",
  path: "stepper",
  // 알림, 상태
  flashbar: "alert",
  messagebar: "alert",
  inlinealert: "alert",
  scopednotifications: "alert",
  snackbar: "toast",
  sonner: "toast",
  loading: "spinner",
  spin: "spinner",
  progressspinner: "spinner",
  progresscircle: "progress",
  progressring: "progress",
  radialprogress: "progress",
  statuslight: "badge",
  status: "badge",
  indicator: "badge",
  iconindicator: "badge",
  shapeindicator: "badge",
  counter: "badge",
  counterlabel: "badge",
  statelabel: "badge",
  labelgroup: "badge",
  branchname: "badge",
  trialbar: "banner",
  ratingdisplay: "meter",
  metergroup: "meter",
  blankslate: "empty",
  nonidealstate: "empty",
  emptystate: "empty",
  illustratedmessage: "empty",
  illustration: "empty",
  result: "empty",
  // 배경, 글자
  section: "card",
  paper: "card",
  panel: "card",
  tile: "card",
  tilegroup: "card",
  tiles: "card",
  well: "card",
  cardfooter: "card",
  cardheader: "card",
  cardpreview: "card",
  html: "prose",
  textcontent: "prose",
  paragraph: "prose",
  orderedlist: "prose",
  unorderedlist: "prose",
  hr: "divider",
  linkoverlay: "link",
  persona: "avatar",
  avatarstack: "avatar",
  skeletonavatar: "skeleton",
  skeletonbox: "skeleton",
  scrollshadow: "scrollarea",
  details: "collapsible",
  summarydetail: "collapsible",
  disclosuregroup: "accordion",
  builderheader: "pageheader",
  entitytitle: "pageheader",
  chat: "bubble",
  files: "attachment",
  // 목록, 표, 그림
  datalist: "listrow",
  keyvaluepairs: "listrow",
  namevaluelist: "listrow",
  labeledvalue: "listrow",
  structuredlist: "listrow",
  orderlist: "listrow",
  item: "listrow",
  dataview: "datatable",
  datascroller: "datatable",
  treetable: "datatable",
  tableview: "datatable",
  // grommet Data*는 전부 DataTable 하위 컴포넌트
  data: "datatable",
  datafilter: "datatable",
  dataclearfilters: "datatable",
  datafilters: "datatable",
  datasearch: "datatable",
  datasort: "datatable",
  datasummary: "datatable",
  datatablecolumns: "datatable",
  datatablegroupby: "datatable",
  areachart: "chart",
  barchart: "chart",
  linechart: "chart",
  mixedlinebarchart: "chart",
  piechart: "chart",
  datachart: "chart",
  // 배지
  filetokengroup: "chip",
  tageditor: "chip",
  token: "chip",
  tokengroup: "chip",
  taggroup: "chip",
  interactiontag: "chip",
  topictag: "chip",
  // 레이아웃 셸
  offcanvas: "sheet",
  placeholder: "skeleton",
  ratio: "aspectratio",

  listy: "listrow", // antd가 List 폐기 후 내놓은 가상 목록
  descriptions: "listrow", // 라벨과 값 쌍 표시 영역
  search: "input", // carbon Search, 이미 넣은 searchbox, searchfield와 한 벌
  fluidtimepickerselect: "select",
  codesnippet: "kbd", // code, codeblock, codeview kbd 래핑 처리

  // flex, grid 등 레이아웃, 유틸리티류는 의도적 제외
};

// 단수, 복수 접미사 한 겹만 제거
function singular(n: string): string[] {
  const out = [n];
  if (n.endsWith("ies")) out.push(n.slice(0, -3) + "y");
  if (n.endsWith("es")) out.push(n.slice(0, -2));
  if (n.endsWith("s")) out.push(n.slice(0, -1));
  return out;
}

export function resolveTokenGroup(
  slug: string,
  title: string | null | undefined,
  available: Set<string>,
): string | null {
  const cands: string[] = [];
  for (const raw of [slug, title ?? ""]) {
    if (!raw) continue;
    const n = norm(raw);
    if (!n) continue;
    cands.push(n);
    const a = ALIAS[n];
    if (a) cands.push(a);
    for (const s of singular(n)) {
      cands.push(s);
      const as = ALIAS[s];
      if (as) cands.push(as);
    }
  }
  for (const c of cands) if (available.has(c)) return c;
  return null;
}
