/* 자동 생성 — tools/gen_blueprint_demos.py. 손으로 고치지 말 것.
 * ⚠️ 경로를 템플릿으로 만들지 않는다 — 번들러가 폴더 전체를 끌어온다. 슬러그마다 명시한 import 함수.
 */
export const SOURCE = {"repo": "palantir/blueprint", "tag": "@blueprintjs/core@6.18.0", "commit": "a60d4c92257612808fbfac81cfeee4fcba91a8b4"};

const DEMO_LOADERS: Record<string, () => Promise<{ DEMOS: Record<string, unknown>; SKIPPED: Record<string, { code: string; codes: string[]; detail: string }>; PENDING: Record<string, { reason: string; detail: string }> }>> = {
  "alert": () => import("./alert/index"),
  "breadcrumbs": () => import("./breadcrumbs/index"),
  "button-group": () => import("./button-group/index"),
  "buttons": () => import("./buttons/index"),
  "callout": () => import("./callout/index"),
  "card": () => import("./card/index"),
  "card-list": () => import("./card-list/index"),
  "collapse": () => import("./collapse/index"),
  "components": () => import("./components/index"),
  "context-menu-popover": () => import("./context-menu-popover/index"),
  "context-menu": () => import("./context-menu/index"),
  "control-card": () => import("./control-card/index"),
  "dialog": () => import("./dialog/index"),
  "divider": () => import("./divider/index"),
  "drawer": () => import("./drawer/index"),
  "editable-text": () => import("./editable-text/index"),
  "entity-title": () => import("./entity-title/index"),
  "checkbox": () => import("./checkbox/index"),
  "control-group": () => import("./control-group/index"),
  "file-input": () => import("./file-input/index"),
  "form-group": () => import("./form-group/index"),
  "input-group": () => import("./input-group/index"),
  "label": () => import("./label/index"),
  "numeric-input": () => import("./numeric-input/index"),
  "radio": () => import("./radio/index"),
  "switch": () => import("./switch/index"),
  "text-area": () => import("./text-area/index"),
  "hotkeys-target": () => import("./hotkeys-target/index"),
  "html": () => import("./html/index"),
  "html-select": () => import("./html-select/index"),
  "html-table": () => import("./html-table/index"),
  "icon": () => import("./icon/index"),
  "link": () => import("./link/index"),
  "menu": () => import("./menu/index"),
  "navbar": () => import("./navbar/index"),
  "non-ideal-state": () => import("./non-ideal-state/index"),
  "overflow-list": () => import("./overflow-list/index"),
  "overlay": () => import("./overlay/index"),
  "overlay2": () => import("./overlay2/index"),
  "panel-stack": () => import("./panel-stack/index"),
  "menu-item": () => import("./menu-item/index"),
  "popover": () => import("./popover/index"),
  "popover-next": () => import("./popover-next/index"),
  "portal": () => import("./portal/index"),
  "progress-bar": () => import("./progress-bar/index"),
  "resize-sensor": () => import("./resize-sensor/index"),
  "section": () => import("./section/index"),
  "segmented-control": () => import("./segmented-control/index"),
  "skeleton": () => import("./skeleton/index"),
  "sliders": () => import("./sliders/index"),
  "spinner": () => import("./spinner/index"),
  "tabs": () => import("./tabs/index"),
  "compound-tag": () => import("./compound-tag/index"),
  "tag": () => import("./tag/index"),
  "tag-input": () => import("./tag-input/index"),
  "text": () => import("./text/index"),
  "toast": () => import("./toast/index"),
  "tooltip": () => import("./tooltip/index"),
  "tree": () => import("./tree/index"),
  "blueprint-provider": () => import("./blueprint-provider/index"),
  "context": () => import("./context/index"),
  "hotkeys-provider": () => import("./hotkeys-provider/index"),
  "overlays-provider": () => import("./overlays-provider/index"),
  "portal-provider": () => import("./portal-provider/index"),
  "accessibility": () => import("./accessibility/index"),
  "classes": () => import("./classes/index"),
  "colors": () => import("./colors/index"),
  "index": () => import("./index/index"),
  "typography": () => import("./typography/index"),
  "variables": () => import("./variables/index"),
  "hooks": () => import("./hooks/index"),
  "use-hotkeys": () => import("./use-hotkeys/index"),
  "use-overlay-stack": () => import("./use-overlay-stack/index"),
};

const EXAMPLE_LOADERS: Record<string, () => Promise<{ DOC_SOURCE: string; EXAMPLES: unknown[]; MASTER: unknown }>> = {
  "alert": () => import("./alert/examples"),
  "breadcrumbs": () => import("./breadcrumbs/examples"),
  "button-group": () => import("./button-group/examples"),
  "buttons": () => import("./buttons/examples"),
  "callout": () => import("./callout/examples"),
  "card": () => import("./card/examples"),
  "card-list": () => import("./card-list/examples"),
  "collapse": () => import("./collapse/examples"),
  "components": () => import("./components/examples"),
  "context-menu-popover": () => import("./context-menu-popover/examples"),
  "context-menu": () => import("./context-menu/examples"),
  "control-card": () => import("./control-card/examples"),
  "dialog": () => import("./dialog/examples"),
  "divider": () => import("./divider/examples"),
  "drawer": () => import("./drawer/examples"),
  "editable-text": () => import("./editable-text/examples"),
  "entity-title": () => import("./entity-title/examples"),
  "checkbox": () => import("./checkbox/examples"),
  "control-group": () => import("./control-group/examples"),
  "file-input": () => import("./file-input/examples"),
  "form-group": () => import("./form-group/examples"),
  "input-group": () => import("./input-group/examples"),
  "label": () => import("./label/examples"),
  "numeric-input": () => import("./numeric-input/examples"),
  "radio": () => import("./radio/examples"),
  "switch": () => import("./switch/examples"),
  "text-area": () => import("./text-area/examples"),
  "hotkeys-target": () => import("./hotkeys-target/examples"),
  "html": () => import("./html/examples"),
  "html-select": () => import("./html-select/examples"),
  "html-table": () => import("./html-table/examples"),
  "icon": () => import("./icon/examples"),
  "link": () => import("./link/examples"),
  "menu": () => import("./menu/examples"),
  "navbar": () => import("./navbar/examples"),
  "non-ideal-state": () => import("./non-ideal-state/examples"),
  "overflow-list": () => import("./overflow-list/examples"),
  "overlay": () => import("./overlay/examples"),
  "overlay2": () => import("./overlay2/examples"),
  "panel-stack": () => import("./panel-stack/examples"),
  "menu-item": () => import("./menu-item/examples"),
  "popover": () => import("./popover/examples"),
  "popover-next": () => import("./popover-next/examples"),
  "portal": () => import("./portal/examples"),
  "progress-bar": () => import("./progress-bar/examples"),
  "resize-sensor": () => import("./resize-sensor/examples"),
  "section": () => import("./section/examples"),
  "segmented-control": () => import("./segmented-control/examples"),
  "skeleton": () => import("./skeleton/examples"),
  "sliders": () => import("./sliders/examples"),
  "spinner": () => import("./spinner/examples"),
  "tabs": () => import("./tabs/examples"),
  "compound-tag": () => import("./compound-tag/examples"),
  "tag": () => import("./tag/examples"),
  "tag-input": () => import("./tag-input/examples"),
  "text": () => import("./text/examples"),
  "toast": () => import("./toast/examples"),
  "tooltip": () => import("./tooltip/examples"),
  "tree": () => import("./tree/examples"),
  "blueprint-provider": () => import("./blueprint-provider/examples"),
  "context": () => import("./context/examples"),
  "hotkeys-provider": () => import("./hotkeys-provider/examples"),
  "overlays-provider": () => import("./overlays-provider/examples"),
  "portal-provider": () => import("./portal-provider/examples"),
  "accessibility": () => import("./accessibility/examples"),
  "classes": () => import("./classes/examples"),
  "colors": () => import("./colors/examples"),
  "index": () => import("./index/examples"),
  "typography": () => import("./typography/examples"),
  "variables": () => import("./variables/examples"),
  "hooks": () => import("./hooks/examples"),
  "use-hotkeys": () => import("./use-hotkeys/examples"),
  "use-overlay-stack": () => import("./use-overlay-stack/examples"),
};

/** 이 베이스 슬러그가 아니면 `null`. 빈 객체를 주지 않는다 — 둘은 다른 뜻이다. */
export function loadDemos(slug: string) {
  const load = DEMO_LOADERS[slug];
  return load ? load() : null;
}

export function loadExamples(slug: string) {
  const load = EXAMPLE_LOADERS[slug];
  return load ? load() : null;
}
