/* 자동 생성 — tools/gen_blueprint_demos.py. 손으로 고치지 말 것. 예제 모듈을 부르지 않는다(문서 칸만). */
export const DOC_SOURCE = "palantir/blueprint@@blueprintjs/core@6.18.0:packages/core/src/components/tag/compound-tag.mdx";
export const EXAMPLES = [
  {
    "key": "CompoundTagBasicExample",
    "name": "Basic",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagBasic.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagIntentExample",
    "name": "Intent",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagIntent.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagMinimalExample",
    "name": "Minimal",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagMinimal.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagSizeExample",
    "name": "Size",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagSize.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagFillExample",
    "name": "Fill",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagFill.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagRoundExample",
    "name": "Round",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagRound.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagIconExample",
    "name": "Icons",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagIcon.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagRemovableExample",
    "name": "Removable",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagRemovable.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagInteractiveExample",
    "name": "Interactive",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTag/CompoundTagInteractive.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "CompoundTagPlaygroundExample",
    "name": "Interactive Playground",
    "axis": "Interactive Playground",
    "kind": "playground",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/compoundTagPlaygroundExample.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  }
];
export const MASTER = {"rule": "doc-order-first", "key": "CompoundTagBasicExample", "reason": null};
