/* 자동 생성 — tools/gen_blueprint_demos.py. 손으로 고치지 말 것. 예제 모듈을 부르지 않는다(문서 칸만). */
export const DOC_SOURCE = "palantir/blueprint@@blueprintjs/core@6.18.0:packages/core/src/components/button/button-group.mdx";
export const EXAMPLES = [
  {
    "key": "ButtonGroupBasicExample",
    "name": "Basic",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupBasic.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupIntentExample",
    "name": "Intent",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupIntent.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupVariantExample",
    "name": "Variant",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupVariant.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupOutlinedMinimalExample",
    "name": "Outlined and minimal",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupOutlinedMinimal.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupSizeExample",
    "name": "Size",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupSize.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupFillExample",
    "name": "Fill",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupFill.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupIconsOnlyExample",
    "name": "Icons only",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupIconsOnly.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupIconsWithTooltipsExample",
    "name": "Icons with tooltips",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupIconsWithTooltips.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupFlexExample",
    "name": "Flex layout",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupFlex.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupVerticalExample",
    "name": "Vertical layout",
    "axis": "Examples",
    "kind": "example",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/button-group/ButtonGroupVertical.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupPopoverExample",
    "name": "Usage with popovers",
    "axis": "Examples",
    "kind": "playground",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  },
  {
    "key": "ButtonGroupPlaygroundExample",
    "name": "Interactive Playground",
    "axis": "Interactive Playground",
    "kind": "playground",
    "description": null,
    "descFormat": null,
    "source": "palantir/blueprint@@blueprintjs/core@6.18.0:packages/docs-app/src/examples/core-examples/buttonGroupPlaygroundExample.tsx",
    "stage": "inline",
    "iframeHeight": null,
    "providerProps": null,
    "args": null
  }
];
export const MASTER = {"rule": "doc-order-first", "key": "ButtonGroupBasicExample", "reason": null};
