/* 자동 생성 — tools/gen_daisyui_demos.py. 손으로 고치지 말 것.
 *
 * ⚠️ 경로를 템플릿으로 만들지 않는다 — 번들러가 폴더 전체를 끌어온다(heroui 판 교훈).
 */
const LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
  "button": () => import("./button.json"),
  "dropdown": () => import("./dropdown.json"),
  "fab": () => import("./fab.json"),
  "modal": () => import("./modal.json"),
  "swap": () => import("./swap.json"),
  "theme-controller": () => import("./theme-controller.json"),
  "accordion": () => import("./accordion.json"),
  "avatar": () => import("./avatar.json"),
  "aura": () => import("./aura.json"),
  "badge": () => import("./badge.json"),
  "card": () => import("./card.json"),
  "carousel": () => import("./carousel.json"),
  "chat": () => import("./chat.json"),
  "collapse": () => import("./collapse.json"),
  "countdown": () => import("./countdown.json"),
  "diff": () => import("./diff.json"),
  "hover-3d": () => import("./hover-3d.json"),
  "hover-gallery": () => import("./hover-gallery.json"),
  "kbd": () => import("./kbd.json"),
  "list": () => import("./list.json"),
  "stat": () => import("./stat.json"),
  "status": () => import("./status.json"),
  "table": () => import("./table.json"),
  "text-rotate": () => import("./text-rotate.json"),
  "timeline": () => import("./timeline.json"),
  "breadcrumbs": () => import("./breadcrumbs.json"),
  "dock": () => import("./dock.json"),
  "link": () => import("./link.json"),
  "megamenu": () => import("./megamenu.json"),
  "menu": () => import("./menu.json"),
  "navbar": () => import("./navbar.json"),
  "pagination": () => import("./pagination.json"),
  "steps": () => import("./steps.json"),
  "tab": () => import("./tab.json"),
  "alert": () => import("./alert.json"),
  "loading": () => import("./loading.json"),
  "progress": () => import("./progress.json"),
  "radial-progress": () => import("./radial-progress.json"),
  "skeleton": () => import("./skeleton.json"),
  "toast": () => import("./toast.json"),
  "tooltip": () => import("./tooltip.json"),
  "calendar": () => import("./calendar.json"),
  "checkbox": () => import("./checkbox.json"),
  "fieldset": () => import("./fieldset.json"),
  "file-input": () => import("./file-input.json"),
  "filter": () => import("./filter.json"),
  "label": () => import("./label.json"),
  "radio": () => import("./radio.json"),
  "range": () => import("./range.json"),
  "rating": () => import("./rating.json"),
  "select": () => import("./select.json"),
  "input": () => import("./input.json"),
  "textarea": () => import("./textarea.json"),
  "toggle": () => import("./toggle.json"),
  "validator": () => import("./validator.json"),
  "otp": () => import("./otp.json"),
  "divider": () => import("./divider.json"),
  "drawer": () => import("./drawer.json"),
  "footer": () => import("./footer.json"),
  "hero": () => import("./hero.json"),
  "indicator": () => import("./indicator.json"),
  "join": () => import("./join.json"),
  "mask": () => import("./mask.json"),
  "stack": () => import("./stack.json"),
  "mockup-browser": () => import("./mockup-browser.json"),
  "mockup-code": () => import("./mockup-code.json"),
  "mockup-phone": () => import("./mockup-phone.json"),
  "mockup-window": () => import("./mockup-window.json"),
};

/** 이 베이스 슬러그가 아니면 `null`. 빈 객체를 주지 않는다 — 둘은 다른 뜻이다. */
export function loadDaisyuiDemoJson(slug: string): Promise<unknown> | null {
  const load = LOADERS[slug];
  return load ? load().then((m) => m.default) : null;
}
