export const THEMES: Record<string,  => Promise<{ byMode: Record<string, unknown> }>> = {
  "01-cobalt":  => import("../../../../generated/01-cobalt/base/cloudscape/theme"),
  "02-graphite":  => import("../../../../generated/02-graphite/base/cloudscape/theme"),
  "03-ember":  => import("../../../../generated/03-ember/base/cloudscape/theme"),
  "04-jade":  => import("../../../../generated/04-jade/base/cloudscape/theme"),
  "05-plum":  => import("../../../../generated/05-plum/base/cloudscape/theme"),
  "06-slate":  => import("../../../../generated/06-slate/base/cloudscape/theme"),
  "07-emerald":  => import("../../../../generated/07-emerald/base/cloudscape/theme"),
  "08-indigo":  => import("../../../../generated/08-indigo/base/cloudscape/theme"),
  "09-sand":  => import("../../../../generated/09-sand/base/cloudscape/theme"),
  "10-teal":  => import("../../../../generated/10-teal/base/cloudscape/theme"),
  "11-crimson":  => import("../../../../generated/11-crimson/base/cloudscape/theme"),
  "12-moss":  => import("../../../../generated/12-moss/base/cloudscape/theme"),
  "13-azure":  => import("../../../../generated/13-azure/base/cloudscape/theme"),
  "14-violet":  => import("../../../../generated/14-violet/base/cloudscape/theme"),
  "15-rust":  => import("../../../../generated/15-rust/base/cloudscape/theme"),
  "16-mint":  => import("../../../../generated/16-mint/base/cloudscape/theme"),
  "17-navy":  => import("../../../../generated/17-navy/base/cloudscape/theme"),
  "18-saffron":  => import("../../../../generated/18-saffron/base/cloudscape/theme"),
  "19-fog":  => import("../../../../generated/19-fog/base/cloudscape/theme"),
  "20-berry":  => import("../../../../generated/20-berry/base/cloudscape/theme"),
};
