export const KO_NAMES: Record<string, string> = {
  "Custom semantic dom styling": "시맨틱 DOM 꾸미기",
  "Basic": "기본",
  "Placement": "놓일 위치",
  "Status": "상태",
  "Size": "크기",
  "Basic Usage": "기본 쓰임",
  "Variants": "변형",
  "Disabled": "못 쓰는 상태",
  "Vertical": "세로",
  "Loading": "불러오는 중",
  "Prefix and Suffix": "앞뒤 장식",
  "Drag sorting": "끌어서 정렬",
  "Dynamic": "그때그때 바꾸기",
  "Icon": "아이콘",
  "Max Count": "최대 개수",
  "Responsive": "반응형",
  "Arrow": "화살표",
  "Auto Shift": "위치 자동 맞춤",
  "Custom dropdown": "직접 만든 드롭다운",
  "Sizes": "크기",
  "Align": "정렬",
  "Asynchronous loading": "비동기로 불러오기",
  "Asynchronously close": "비동기로 닫기",
  "Checkable": "체크할 수 있음",
  "Clickable": "누를 수 있음",
  "Collapsible": "접을 수 있음",
  "Complex combination": "복잡한 조합",
  "Controlled mode": "제어 모드",
  "Custom Wave": "직접 만든 물결",
  "Custom action": "직접 만든 동작",
  "Custom semantic styles": "직접 만든 시맨틱 스타일",
  "Custom trigger": "직접 만든 여는 위치",
  "Customize": "직접 정하기",
  "Drag sorting with handler": "핸들로 끌어서 정렬",
  "Extra node": "덧붙임 마디",
  "Fixed Header": "고정 머리",
  "Focus": "초점",
  "Hooks usage (recommended)": "훅으로 쓰기 (권장)",
  "Horizontal": "가로",
  "Multiple": "여럿 고르기",
  "Need Confirm": "확인 필요",
  "Pagination Settings": "쪽 나누기 설정",
  "Search": "찾기",
  "Stack": "쌓기",
  "Three Sizes": "세 가지 크기",
  "Type": "종류",
  "Update Message Content": "메시지 내용 갱신",
  "Variant": "변형",
  "With Icon": "아이콘 넣기",
  "With clear icon": "지우기 아이콘",
  "Wrap": "줄바꿈",
  "disabled": "못 쓰는 상태",
  "draggable": "끌 수 있음",
  "mask": "막",
  "12 hours": "12시간",
  "403": "403",
  "404": "404",
  "500": "500",
  "= 5.10.0\">Custom count logic": "= 5.10.0\">개수 세는 방법 직접 정하기",
  "= 5.10.0\">Panel": "= 5.10.0\">패널",
  "Accordion": "아코디언",
  "Active Animation": "움직이는 상태",
  "Add & Remove Dynamically": "그때그때 넣고 빼기",
  "Add & close tab": "탭 넣고 닫기",
  "Addon": "덧붙임 필드",
  "Advanced": "고급",
  "Advanced Usage": "고급 쓰임",
  "Advanced search": "고급 찾기",
  "Ajax": "Ajax",
  "Alignment": "맞춤",
  "Aliyun OSS": "Aliyun OSS",
  "Allow Empty": "비워 두기",
  "Alternate": "번갈아",
  "Animate": "움직임",
  "Animated number": "움직이는 숫자",
  "Arrow pointing at the center": "가운데를 가리키는 화살표",
  "Arrows for switching": "넘김 화살표",
  "Asynchronously close on Promise": "Promise 로 비동기 닫기",
  "Auto height": "높이 자동",
  "Automatic tokenization": "자동으로 나누기",
  "Autoset Font Size": "글자 크기 자동",
  "Autosizing the height to fit the content": "내용에 맞춰 높이 자동",
  "Avatar": "아바타",
  "Avatar.Group": "Avatar.Group",
  "BackTop": "맨 위로",
  "Banner": "띠",
  "Basic Grid": "기본 격자",
  "Basic Structure": "기본 구조",
  "Basic card": "기본 카드",
  "Basic list": "기본 목록",
  "Basic usage": "기본 쓰임",
  "Big Data": "큰 데이터",
  "Block Button": "덩어리 버튼",
  "Block Node": "덩어리 마디",
  "Block Radio.Group": "덩어리 Radio.Group",
  "Block Segmented": "덩어리 Segmented",
  "Borderless": "테두리 없음",
  "Bread crumbs with drop down menu": "드롭다운이 있는 Breadcrumb",
  "Buddhist Era": "불기력",
  "Button Compact Mode": "버튼 빽빽 모드",
  "Button with dropdown menu": "드롭다운 메뉴가 있는 버튼",
  "Button/Avatar/Input/Image/Node": "Button/Avatar/Input/Image/Node",
  "Callback": "콜백",
  "Card": "카드",
  "Card in column": "열 안의 카드",
  "Card type tab": "카드 모양 탭",
  "Cascading menu": "이어지는 메뉴",
  "Centered": "가운데",
  "Change on scroll": "굴릴 때 바꾸기",
  "Change on select": "고를 때 바꾸기",
  "Change progress value position": "진행 값 위치 바꾸기",
  "Changer": "바꾸개",
  "Check all": "모두 고르기",
  "Checkbox Group": "Checkbox 그룹",
  "Choose Time": "시각 고르기",
  "Choose image": "이미지 고르기",
  "Circular progress bar": "원형 진행 막대",
  "Circular progress bar with steps": "단계가 있는 원형 진행 막대",
  "Clear Color": "색 지우기",
  "Clear star": "별점 지우기",
  "Click event": "누름 이벤트",
  "Closable": "닫을 수 있음",
  "Closable placement": "닫기 버튼 위치",
  "Collapse": "접기",
  "Collapsed inline menu": "접힌 한 줄 메뉴",
  "Collapsible overlay": "접을 수 있는 덮개",
  "Color & Variant": "색과 변형",
  "Color Format": "색 형식",
  "Colorful Badge": "색 badge",
  "Colorful Tag": "색 Tag",
  "Colorful Tooltip": "색 Tooltip",
  "Column offset": "열 치우침",
  "Compact Mode for form component": "폼 컴포넌트 빽빽 모드",
  "Compact Style": "빽빽한 모양",
  "Complete control over file list": "파일 목록 온전히 다루기",
  "Complex Dynamic Form Item": "복잡한 동적 폼 항목",
  "Component size": "컴포넌트 크기",
  "Conditional trigger": "조건부 열기",
  "ConfigProvider": "ConfigProvider",
  "Configuring the Separator": "구분자 설정",
  "Configuring the Separator Independently": "구분자 따로 설정",
  "Container to scroll.": "굴러가는 상자",
  "Contains sub component": "하위 컴포넌트 포함",
  "Content": "내용",
  "Context Menu": "컨텍스트 메뉴",
  "Control between forms": "폼 사이에서 다루기",
  "Control collapsible icons": "접기 아이콘 다루기",
  "Control mode": "제어 모드",
  "Control visibility of Tooltip": "Tooltip 보임 다루기",
  "Controlled": "제어됨",
  "Controlled Checkbox": "제어되는 Checkbox",
  "Controlled Preview": "제어되는 미리보기",
  "Controlled Tree": "제어되는 Tree",
  "Controlled ellipsis expand/collapse": "제어되는 말줄임 펼치기·접기",
  "Controlling the close of the dialog": "창 닫기 다루기",
  "Copyable": "복사할 수 있음",
  "Crop image before uploading": "올리기 전에 이미지 자르기",
  "Custom": "직접 정하기",
  "Custom Actions": "직접 만든 동작",
  "Custom Color": "직접 정한 색",
  "Custom Field Names": "직접 정한 필드 이름",
  "Custom Icon": "직접 정한 아이콘",
  "Custom Panel": "직접 만든 패널",
  "Custom Placement": "직접 정한 위치",
  "Custom Popup Search": "직접 만든 팝업 찾기",
  "Custom Render": "직접 그리기",
  "Custom Render Panel": "직접 그린 패널",
  "Custom Render Type": "직접 정한 그리기 방식",
  "Custom Search": "직접 만든 찾기",
  "Custom Selected Label Render": "고른 라벨 직접 그리기",
  "Custom Size": "직접 정한 크기",
  "Custom Submenu Render": "직접 그린 하위 메뉴",
  "Custom Tag Render": "직접 그린 태그",
  "Custom Trigger": "직접 만든 여는 위치",
  "Custom Trigger Event": "직접 정한 여는 이벤트",
  "Custom action icon and extra info": "직접 만든 동작 아이콘과 덧붙임 정보",
  "Custom close button": "직접 만든 닫기 버튼",
  "Custom component": "직접 만든 컴포넌트",
  "Custom configuration": "직접 만든 설정",
  "Custom container": "직접 만든 상자",
  "Custom datasource": "직접 만든 데이터",
  "Custom disabled backgroundColor": "못 쓰는 상태의 바탕색 직접 정하기",
  "Custom dropdown options": "직접 만든 드롭다운 항목",
  "Custom empty": "직접 만든 빈 상태",
  "Custom highlighted area style": "직접 정한 강조 영역 모양",
  "Custom icon": "직접 정한 아이콘",
  "Custom indicator": "직접 만든 표시자",
  "Custom line gradient": "직접 정한 선 그러데이션",
  "Custom mask style": "직접 정한 막 모양",
  "Custom modal content render": "창 내용 직접 그리기",
  "Custom preview image": "직접 정한 미리보기 이미지",
  "Custom preview render": "미리보기 직접 그리기",
  "Custom render": "직접 그리기",
  "Custom selection": "직접 만든 선택 항목",
  "Custom size": "직접 정한 크기",
  "Custom spinning indicator": "직접 만든 도는 표시",
  "Custom text format": "직접 정한 글자 형식",
  "Custom title alignment": "직접 정한 제목 정렬",
  "Custom tokenization": "직접 만든 나누기",
  "Custom toolbar render": "도구 막대 직접 그리기",
  "Customize Header": "머리 직접 만들기",
  "Customize Icon": "아이콘 직접 정하기",
  "Customize Input Component": "Input 컴포넌트 직접 만들기",
  "Customize Panel": "패널 직접 만들기",
  "Customize Popup": "팝업 직접 만들기",
  "Customize Progress Bar": "진행 막대 직접 만들기",
  "Customize Trigger Token": "부르는 표시 직접 정하기",
  "Customize character": "글자 직접 정하기",
  "Customize clear button": "지우기 버튼 직접 만들기",
  "Customize collapse/expand icon": "접기·펼치기 아이콘 직접 정하기",
  "Customize duration": "떠 있는 시간 직접 정하기",
  "Customize footer buttons props": "바닥 버튼 prop 직접 정하기",
  "Customize icon": "아이콘 직접 정하기",
  "Customize preview file": "미리보기 파일 직접 만들기",
  "Customize progress bar color": "진행 막대 색 직접 정하기",
  "Customize the anchor highlight": "앵커 강조 직접 만들기",
  "Customize the onClick event": "onClick 직접 정하기",
  "Customize tooltip": "툴팁 직접 정하기",
  "Customized": "직접 정함",
  "Customized Cell Rendering": "셀 직접 그리기",
  "Customized Footer": "직접 만든 바닥",
  "Customized Footer render function": "바닥을 그리는 함수 직접 만들기",
  "Customized Form Controls": "직접 만든 폼 컨트롤",
  "Customized Icon": "직접 만든 검증",
  "Customized Validation": "직접 만든 아이콘",
  "Customized bar of tab": "직접 만든 탭 막대",
  "Customized content": "직접 만든 내용",
  "Customized description": "직접 만든 설명",
  "Customized filter panel": "직접 만든 거르기 패널",
  "Customized trigger of new tab": "새 탭을 여는 위치 직접 만들기",
  "Danger Buttons": "위험 버튼",
  "Dashboard": "계기판",
  "Date Format": "날짜 형식",
  "Default Files": "기본 파일",
  "Default value": "기본값",
  "Delay": "늦추기",
  "Dependencies": "이어진 필드",
  "Description": "설명",
  "Direction": "방향",
  "Disable": "못 쓰게 하기",
  "Disabled Alpha": "투명도 못 씀",
  "Disabled Date & Time": "못 고르는 날짜와 시각",
  "Disabled option": "못 고르는 항목",
  "Disabled per handle": "핸들별로 못 쓰게 하기",
  "Divider with title": "제목이 있는 Divider",
  "Dot Style": "점 모양",
  "Double-clicked reset": "두 번 눌러 되돌리기",
  "Download QRCode": "QR 코드 내려받기",
  "Drag Column sorting": "열 끌어서 정렬",
  "Drag and Drop": "끌어서 놓기",
  "Drag sorting of uploadList": "올린 파일 목록 끌어서 정렬",
  "Draggable Tabs": "끌 수 있는 Tabs",
  "Draggable Tag": "끌 수 있는 Tag",
  "Draggable track": "끌 수 있는 트랙",
  "Duration": "떠 있는 시간",
  "Duration after which the notification box is closed": "알림이 닫히기까지의 시간",
  "Dynamic Form Item": "동적 폼 항목",
  "Dynamic Form nest Items": "겹쳐진 동적 폼 항목",
  "Dynamic Rules": "동적 규칙",
  "Dynamic Settings": "그때그때 바꾸는 설정",
  "Dynamic edit nodes": "마디 그때그때 고치기",
  "Editable": "고칠 수 있음",
  "Editable Cells": "고칠 수 있는 셀",
  "Editable Rows": "고칠 수 있는 행",
  "Ellipsis": "말줄임",
  "Ellipsis from middle": "가운데 말줄임",
  "Embedded mode": "끼워 넣은 모드",
  "End alternate": "끝 번갈아",
  "Error": "오류",
  "Error Level": "오류 정정 수준",
  "Error status": "오류 상태",
  "ErrorBoundary": "ErrorBoundary",
  "Event": "이벤트",
  "Event Range": "일정 범위",
  "Expandable Row": "펼칠 수 있는 행",
  "External use panel": "바깥에서 패널 쓰기",
  "Extra Actions": "덧붙임 동작",
  "Extra Footer": "덧붙임 바닥",
  "Extra content": "덧붙임 내용",
  "Fade in": "흐려지며 나타나기",
  "Fault tolerant": "못 불러왔을 때",
  "Filled": "채움",
  "Filter and sorter": "거르기와 정렬",
  "Filter in Tree": "Tree 에서 거르기",
  "Filter search": "거르기 찾기",
  "Fixed Columns": "고정 열",
  "Fixed Columns and Header": "고정 열과 머리",
  "Fixed Sider": "고정 사이드바",
  "Fixed header and scroll bar with the page": "쪽을 따라오는 고정 머리와 스크롤 막대",
  "Flex Responsive": "Flex 반응형",
  "Flex Stretch": "Flex 늘리기",
  "FloatButton Group": "FloatButton 그룹",
  "FloatButton with tooltip": "툴팁이 있는 FloatButton",
  "Form Layout": "폼 배치",
  "Form disabled": "못 쓰는 폼",
  "Form in Modal to Create": "Modal 안의 폼으로 만들기",
  "Form methods": "폼 메서드",
  "Form mix layout": "폼 배치 섞기",
  "Form size": "폼 크기",
  "Form variants": "폼 변형",
  "Format Tooltip Input": "Tooltip 입력 형식 맞추기",
  "Formatter": "형식 맞추개",
  "Fullscreen": "전체 화면",
  "Generate from tree data": "트리 데이터로 만들기",
  "Get value of selected item": "고른 항목의 값 받기",
  "Ghost Button": "유령 버튼",
  "Ghost Collapse": "유령 Collapse",
  "Gradient Button": "그러데이션 버튼",
  "Gradients": "그러데이션",
  "Graduated slider": "눈금이 있는 슬라이더",
  "Grid": "격자",
  "Grid Drag sorting": "격자 끌어서 정렬",
  "Grid Drag sorting with handler": "핸들로 격자 끌어서 정렬",
  "Grid Gutter": "격자 간격",
  "Grid card": "격자 카드",
  "Grid sort": "격자 정렬",
  "Grouping and sticky headers": "묶기와 붙는 머리",
  "Grouping table head": "표 머리 묶기",
  "Half star": "반 별점",
  "Handle Form Data Manually": "폼 데이터 직접 다루기",
  "Header Sider 2": "머리와 사이드바 2",
  "Header-Content-Footer": "머리-내용-바닥",
  "Header-Sider": "머리-사이드바",
  "Hidden Columns": "숨긴 열",
  "Hide Already Selected": "이미 고른 것 숨기기",
  "High precision decimals": "아주 정밀한 소수",
  "Hooks config": "훅 설정",
  "Horizontal Anchor": "가로 Anchor",
  "Hour and minute": "시와 분",
  "Hover": "마우스 올림",
  "Hover with click popover": "올리고 눌러서 popover",
  "Icon Placement": "아이콘 위치",
  "Image": "이미지",
  "Image watermark": "이미지 워터마크",
  "In Card": "Card 안에서",
  "Indicator": "표시자",
  "Infinite loading": "끝없이 불러오기",
  "Info": "안내",
  "Inline Login Form": "한 줄 로그인 폼",
  "Inline Steps": "한 줄 단계",
  "Inline Style Combination": "인라인 스타일 조합",
  "Inline menu": "한 줄 메뉴",
  "Inner card": "안쪽 카드",
  "Internationalization": "여러 언어",
  "JSX style API": "JSX 방식 API",
  "Jumper": "쪽 건너뛰기",
  "Keyboard": "자판",
  "Lazy": "느긋하게",
  "Limit Date Range": "날짜 범위 제한",
  "Line Gradient": "선 그러데이션",
  "Line width": "선 굵기",
  "List": "목록",
  "Listening for anchor link change": "앵커 링크 바뀜 지켜보기",
  "Load Options Lazily": "항목 늦게 불러오기",
  "Load more": "더 불러오기",
  "Loading and Reversing": "불러오는 중과 뒤집기",
  "Loading card": "불러오는 중 카드",
  "Locale": "언어 설정",
  "Locale text": "언어별 글",
  "Login Form": "로그인 폼",
  "Lookup-Patterns - Certain Category": "찾아보기, 종류가 정해진 경우",
  "Lookup-Patterns - Uncertain Category": "찾아보기, 종류가 정해지지 않은 경우",
  "Loop Banner": "도는 띠",
  "Lunar Calendar": "음력",
  "Manual to update destroy": "직접 갱신하고 없애기",
  "Mask Format": "가리는 형식",
  "Menu Themes": "메뉴 테마",
  "Menu mode": "메뉴 모드",
  "Menu tooltip": "메뉴 툴팁",
  "Message with loading indicator": "불러오는 중 표시가 있는 메시지",
  "Mini size circular progress bar": "아주 작은 원형 진행 막대",
  "Mini size progress bar": "아주 작은 진행 막대",
  "Modal or Drawer": "Modal 이나 Drawer",
  "More": "더 보기",
  "More responsive": "더 촘촘한 반응형",
  "More types": "더 많은 종류",
  "Multi field search": "여러 필드 찾기",
  "Multi-level drawer": "여러 겹 서랍",
  "Multi-line watermark": "여러 줄 워터마크",
  "Multiple Buttons": "버튼 여럿",
  "Multiple Selection": "여럿 고르기",
  "Multiple beams": "빛줄기 여럿",
  "Multiple handles": "핸들 여럿",
  "Multiple image preview": "이미지 여럿 미리보기",
  "Multiple panels": "패널 여럿",
  "Multiple resources from iconfont.cn": "iconfont.cn 자원 여럿",
  "Multiple sorter": "정렬 여럿",
  "Navigation Steps": "길잡이 단계",
  "Nest": "겹치기",
  "Nested panel": "겹쳐진 패널",
  "Nested tables": "겹쳐진 표",
  "No arrow": "화살표 없음",
  "No block rule": "막지 않는 규칙",
  "No border": "테두리 없음",
  "No description": "설명 없음",
  "Non-case-sensitive AutoComplete": "대소문자 안 가리는 AutoComplete",
  "Non-modal": "덮지 않는 모드",
  "Notice Calendar": "알림 달력",
  "Notification with icon": "아이콘이 있는 알림",
  "OTP": "OTP",
  "Offset": "치우침",
  "One Way": "한 방향",
  "Open current submenu only": "지금 하위 메뉴만 열기",
  "Option Group": "항목 그룹",
  "Order": "순서",
  "Order Specific Column": "특정 열 순서",
  "Other Character": "다른 글자",
  "Other Form Controls": "다른 폼 컨트롤",
  "Other elements": "다른 요소",
  "Other types of message": "다른 종류의 메시지",
  "Out of range": "범위 벗어남",
  "Overflow Count": "넘침 개수",
  "Pagination": "쪽 나누기",
  "Panel Steps": "패널 모양 단계",
  "Panel with icon": "아이콘이 있는 패널",
  "Password box": "비밀번호 입력칸",
  "Paste": "붙여넣기",
  "Path Prefix": "경로 앞머리",
  "Pictures Wall": "사진 벽",
  "Pictures with list style": "목록 모양 사진",
  "Pictures with picture-circle type": "picture-circle 모양 사진",
  "Playground": "놀이터",
  "Position": "위치",
  "Prefix / Suffix": "앞뒤 장식",
  "Preset Colors": "미리 둔 색",
  "Preset Ranges": "미리 둔 범위",
  "Preset size": "미리 둔 크기",
  "Prev and next": "이전과 다음",
  "Preview drawer": "미리보기 서랍",
  "Preview from one image": "이미지 하나에서 미리보기",
  "Progress": "진행",
  "Progress bar": "진행 막대",
  "Progress bar with steps": "단계가 있는 진행 막대",
  "Progress bar with success segment": "성공 구간이 있는 진행 막대",
  "Progress of dots": "점으로 보는 진행",
  "Progress ring": "진행 고리",
  "Progress size": "진행 크기",
  "Progressive Loading": "점점 불러오기",
  "Promise interface": "Promise 방식",
  "Radio Group": "Radio 그룹",
  "Radio.Group group - optional": "Radio.Group 그룹, 선택",
  "Radio.Group with name": "name 이 있는 Radio.Group",
  "Range Picker": "범위 고르개",
  "Read only": "읽기 전용",
  "Red badge": "빨간 badge",
  "Registration": "가입",
  "Render in current dom": "지금 DOM 에 그리기",
  "Rendering Trigger Text": "여는 글자 그리기",
  "Replace href in history": "방문 기록 바꿔치기",
  "Required style": "필수 표시 모양",
  "Reset filters and sorters": "거르기와 정렬 되돌리기",
  "Resizable": "크기 바꾸기",
  "Responsive Size": "반응형 크기",
  "Responsive circular progress bar": "반응형 원형 진행 막대",
  "Responsive grid list": "반응형 격자 목록",
  "Responsive maxTagCount": "반응형 maxTagCount",
  "Reverse": "뒤집기",
  "Ribbon": "리본",
  "Rich content": "풍성한 내용",
  "Round shape": "둥근 모양",
  "Scroll automatically": "저절로 넘기기",
  "Scroll to nested node": "겹쳐진 마디로 굴러가기",
  "Scrolling loaded": "굴리며 불러오기",
  "Search and Select Users": "사용자 찾아 고르기",
  "Search box": "찾기 상자",
  "Search box with loading": "불러오는 중 표시가 있는 찾기 상자",
  "Search with sort": "찾고 정렬하기",
  "Searchable": "찾을 수 있음",
  "Select range dates": "날짜 범위 고르기",
  "Select with search field": "찾기 필드가 있는 Select",
  "Selectable Calendar": "고를 수 있는 달력",
  "Selectable Menu": "고를 수 있는 메뉴",
  "Selection actions": "선택 동작",
  "Selection and operation": "고르기와 처리",
  "Semantic Sample": "시맨틱 표본",
  "Set Anchor scroll offset": "Anchor 굴림 치우침 정하기",
  "Set the spacing size of the divider": "구분선 간격 크기 정하기",
  "Shape": "모양",
  "Shared column props": "공통 열 prop",
  "Show All": "모두 보이기",
  "Show Tree Line": "트리 선 보이기",
  "Show Week": "주 보이기",
  "Show copywriting": "문구 보이기",
  "Show on hover": "올렸을 때 보이기",
  "Show with progress": "진행과 함께 보이기",
  "ShowCheckedStrategy": "ShowCheckedStrategy",
  "Sider": "사이드바",
  "Simple card": "간단한 카드",
  "Simple list": "간단한 목록",
  "Simple mode": "간단 모드",
  "Slide": "슬라이드",
  "Slide to error field": "오류 필드로 굴러가기",
  "Slider with InputNumber": "InputNumber 가 있는 Slider",
  "Slider with icon": "아이콘이 있는 Slider",
  "Smooth Transition": "부드럽게 넘어가기",
  "Smoothly Unmount": "부드럽게 걷어 내기",
  "Solid radio button": "solid 라디오 버튼",
  "Space Size": "간격 크기",
  "Spinner": "도는 표시",
  "Stack Fixed Columns": "고정 열 쌓기",
  "Standalone": "홑으로 쓰기",
  "Static Anchor": "정적 Anchor",
  "Static Method": "정적 메서드",
  "Static Method (deprecated)": "정적 메서드 (폐기됨)",
  "Static confirmation": "정적 확인창",
  "Static function": "정적 함수",
  "Static method (deprecated)": "정적 메서드 (폐기됨)",
  "Status Tag": "상태 Tag",
  "Store Form Data into Upper Component": "폼 데이터를 위 컴포넌트에 담기",
  "Stroke Linecap": "선 끝 모양",
  "Sub-menu theme": "하위 메뉴 테마",
  "Submit form in drawer": "서랍 안에서 폼 보내기",
  "Success": "성공",
  "Summary": "요약",
  "Support more content configuration": "더 많은 내용 설정",
  "Switch the menu type": "메뉴 종류 바꾸기",
  "Switchable picker": "바꿀 수 있는 고르개",
  "Syntactic sugar": "줄임말",
  "Table": "표",
  "Table Transfer": "표 옮기기",
  "Tags": "태그",
  "Text & icon": "글자와 아이콘",
  "Text and Link Component": "Text 와 Link 컴포넌트",
  "Text without heading style": "제목 모양이 아닌 글",
  "TextArea": "TextArea",
  "The way of hiding menu.": "메뉴를 숨기는 방법",
  "Theme": "테마",
  "Three sizes of Input": "Input 의 세 가지 크기",
  "Three sizes of Segmented": "Segmented 의 세 가지 크기",
  "Three ways to trigger": "여는 방법 세 가지",
  "Time Range Picker": "시각 범위 고르개",
  "Time-related Controls": "시각 관련 컨트롤",
  "Timer": "타이머",
  "Title": "제목",
  "Title Component": "Title 컴포넌트",
  "Title Offset": "제목 치우침",
  "Title Placement and Progress": "제목 위치와 진행",
  "To customize the position of modal": "창 위치 직접 정하기",
  "To customize the width of modal": "창 너비 직접 정하기",
  "Top Navigation": "위쪽 길잡이",
  "Total number": "전체 개수",
  "Transform file before request": "보내기 전에 파일 손보기",
  "Tree Transfer": "트리 옮기기",
  "Tree data": "트리 데이터",
  "Tree with line": "선이 있는 트리",
  "Trigger mode": "여는 방식",
  "Trigger size": "여는 버튼 크기",
  "Two sizes": "두 가지 크기",
  "Two-tone icon and colorful icon": "두 색 아이콘과 색 아이콘",
  "Typesetting": "활자 짜기",
  "Under Control": "제어 아래에서",
  "Unit": "단위",
  "Upload by clicking": "눌러서 올리기",
  "Upload directory": "폴더 올리기",
  "Upload manually": "직접 올리기",
  "Upload png file only": "png 만 올리기",
  "Use hooks to get context": "훅으로 context 받기",
  "Use iconfont.cn": "iconfont.cn 쓰기",
  "Use with Grid": "Grid 와 함께 쓰기",
  "Validate Only": "검증만 하기",
  "Validate Trigger": "검증 시점",
  "Vertical Compact Mode": "세로 빽빽 모드",
  "Vertical Direction": "세로 방향",
  "Vertical Radio.Group": "세로 Radio.Group",
  "Vertical Space": "세로 Space",
  "Vertical border": "세로 테두리",
  "Vertical menu": "세로 메뉴",
  "Virtual list": "가상 목록",
  "Virtual scroll": "가상 스크롤",
  "Virtual scrolling": "가상 스크롤",
  "Warning": "경고",
  "Watch Hooks": "Watch 훅",
  "Wheel": "휠",
  "With Badge": "Badge 와 함께",
  "With Form": "Form 과 함께",
  "With Icon only": "아이콘만",
  "With Params": "값과 함께",
  "With an Icon": "아이콘과 함께",
  "With character counting": "글자 수 세기",
  "With icon": "아이콘과 함께",
  "With name": "name 과 함께",
  "With tabs": "탭과 함께",
  "Wrap custom component": "직접 만든 컴포넌트 감싸기",
  "align": "정렬",
  "autoSize": "autoSize",
  "badge": "badge",
  "base": "기본",
  "border": "테두리",
  "border, title and footer": "테두리·제목·바닥",
  "colSpan and rowSpan": "colSpan 과 rowSpan",
  "combination": "조합",
  "complex form control": "복잡한 폼 컨트롤",
  "controlled mode": "제어 모드",
  "coordinate": "맞물려 고르기",
  "custom status render": "직접 만든 상태 그리기",
  "destroy confirmation modal dialog": "확인창 없애기",
  "directory": "폴더",
  "disabled or readOnly": "disabled 나 readOnly",
  "ellipsis column": "말줄임 열",
  "ellipsis column custom tooltip": "말줄임 열의 툴팁 직접 정하기",
  "gap": "간격",
  "getValueProps + normalize": "getValueProps + normalize",
  "interval option": "간격 항목",
  "label can wrap": "라벨 줄바꿈",
  "load data asynchronously": "데이터 비동기로 불러오기",
  "maxCount includes overflow": "maxCount 에 넘침 포함",
  "multiple selection": "여럿 고르기",
  "nested": "겹치기",
  "other status": "다른 상태",
  "placement": "놓일 위치",
  "prefix and suffix": "앞뒤 장식",
  "preview mask": "미리보기 막",
  "radio style": "라디오 모양",
  "responsive": "반응형",
  "row": "행",
  "selection": "고르기",
  "separator": "구분자",
  "size": "크기",
  "suffix": "뒤 장식",
  "useBreakpoint Hook": "useBreakpoint 훅",
  "virtual list": "가상 목록",
};
