export const KO_PARTS: Record<string, string> = {
  "Container element, set background color, padding, border radius, shadow, border and content display styles": "담는 상자 요소. 바탕색·안쪽 여백·모서리·그림자·선, 그리고 내용을 어떻게 늘어놓을지가 여기 걸려요",
  "Multiple selection container with layout, spacing, and wrapping styles for selected items": "여럿 고른 항목을 담는 상자. 고른 항목들의 배치·간격·줄바꿈이 여기 걸려요",
  "Placeholder element with font styles and colors for placeholder text": "플레이스홀더 요소. 안내 글의 글꼴과 색이 여기 걸려요",
  "Arrow element with width, height, position, color and border styles": "화살표 요소. 너비·높이·위치·색·선이 여기 걸려요",
  "Clear button element with layout, styling and interactive effects for clear button": "지우기 버튼 요소. 배치와 모양, 누를 때의 반응이 여기 걸려요",
  "Input element with search input styling, cursor control, font inheritance and other search-related styles. Remove border styles": "입력 요소. 검색 입력 모양·커서·글꼴 상속 같은 검색 관련 규칙이 여기 걸리고, 선은 없애요",
  "Multiple selection item content area with text ellipsis styles": "여럿 고르기 항목의 내용 영역. 글이 넘칠 때 말줄임이 여기 걸려요",
  "Multiple selection item element with border, background, padding, and margin styles": "여럿 고르기 항목 요소. 선·바탕·안쪽 여백·바깥 여백이 여기 걸려요",
  "Multiple selection item remove button with font-related styles": "여럿 고르기 항목의 지우기 버튼. 글꼴 관련 규칙이 여기 걸려요",
  "Popup element with popup layer positioning, z-index, background, border, box-shadow and other popup container styles": "팝업 요소. 떠 있는 층의 위치·z-index·바탕·선·그림자 같은 팝업 상자 규칙이 여기 걸려요",
  "Popup item element with option item padding, hover effects, selected states, disabled states and other option interactive styles": "팝업 항목 요소. 고를 항목의 안쪽 여백, 마우스 올림·고름·못 씀 같은 상태별 반응이 여기 걸려요",
  "Popup list element with option list layout, scrolling, max-height and other list container styles": "팝업 목록 요소. 고를 항목 목록의 배치·스크롤·최대 높이 같은 목록 상자 규칙이 여기 걸려요",
  "Prefix element with layout and styling for prefix content": "앞 장식 요소. 앞에 붙는 내용의 배치와 모양이 여기 걸려요",
  "Root element with relative positioning, inline-flex layout, cursor styles, transitions, border and other basic selector container styles": "뿌리 요소. relative 자리잡기, inline-flex 배치, 커서, 전환, 선 같은 선택칸 상자의 기본 규칙이 여기 걸려요",
  "Close button element with basic button styling": "닫기 버튼 요소. 버튼의 기본 모양이 여기 걸려요",
  "Input element with relative positioning, width, color, font, line-height, transition animations and other core interactive styles for input field": "입력 요소. relative 자리잡기, 너비, 색, 글꼴, 줄 높이, 전환 같은 입력칸의 핵심 규칙이 여기 걸려요",
  "Popup content element with width, border, cell and other content display styles for date table": "팝업 내용 요소. 날짜 표의 너비·선·셀 같은 내용 표시 규칙이 여기 걸려요",
  "Popup element": "팝업 요소",
  "Popup footer element with layout styles for bottom operation area including confirm/cancel buttons and shortcuts": "팝업 바닥 요소. 확인·취소 버튼과 바로가기가 놓이는 아래쪽 조작 영역의 배치가 여기 걸려요",
  "Popup item element with size, background, border-radius, hover state, selected state and other interactive styles for date cells": "팝업 항목 요소. 날짜 셀의 크기·바탕·모서리와 마우스 올림·고름 같은 상태별 반응이 여기 걸려요",
  "Prefix element with flex layout and margin styles for prefix content layout": "앞 장식 요소. 앞에 붙는 내용의 flex 배치와 바깥 여백이 여기 걸려요",
  "Preview close button element, sets basic button styles": "미리보기 닫기 버튼 요소. 버튼의 기본 모양이 여기 걸려요",
  "Root element with relative positioning, inline-flex layout, padding, border-radius, transition animations and other basic styles for date picker container": "뿌리 요소. relative 자리잡기, inline-flex 배치, 안쪽 여백, 모서리, 전환 같은 날짜 고르개 상자의 기본 규칙이 여기 걸려요",
  "Root element, set absolute positioning, z-index, transform origin, arrow direction and popover container styles": "뿌리 요소. absolute 자리잡기, z-index, 변형 기준점, 화살표 방향 같은 popover 상자 규칙이 여기 걸려요",
  "Suffix element with flex layout, color, line-height, pointer events, transition animations and other styles for suffix content": "뒤 장식 요소. flex 배치, 색, 줄 높이, 포인터 이벤트, 전환 같은 규칙이 여기 걸려요",
  "Suffix element with layout and styling for suffix content like clear button, arrow icon, etc.": "뒤 장식 요소. 지우기 버튼이나 화살표 아이콘처럼 뒤에 붙는 내용의 배치와 모양이 여기 걸려요",
  "Title element, set title text styles and spacing": "제목 요소. 제목 글의 모양과 간격이 여기 걸려요",
  "Action area element with margin, text alignment, inner element spacing and other layout styles": "동작 영역 요소. 바깥 여백, 글 정렬, 안쪽 요소 간격 같은 배치가 여기 걸려요",
  "Action button group container with left auto margin, button spacing and other button group layout styles": "동작 버튼 그룹 상자. 왼쪽 자동 여백과 버튼 간격 같은 버튼 그룹 배치가 여기 걸려요",
  "Actions element with layout and spacing styles for action buttons": "동작 요소. 동작 버튼들의 배치와 간격이 여기 걸려요",
  "Actions element with layout and spacing styles for copy, edit, expand/collapse buttons": "동작 요소. 복사·편집·펼침/접힘 버튼의 배치와 간격이 여기 걸려요",
  "Actions element with transfer button group styles, layout and interaction states": "동작 요소. 옮기기 버튼 그룹의 모양·배치·상태가 여기 걸려요",
  "Actions element, set float right, top margin and action button layout styles": "동작 요소. 오른쪽 띄우기, 위쪽 바깥 여백, 동작 버튼 배치가 여기 걸려요",
  "Actions element, sets absolute positioning, width, flex layout and number adjustment button styles": "동작 요소. absolute 자리잡기, 너비, flex 배치, 숫자 조절 버튼 모양이 여기 걸려요",
  "Avatar element with inline-block display, vertical alignment, background color, size, border radius and other avatar placeholder styles": "아바타 요소. inline-block 표시, 세로 정렬, 바탕색, 크기, 모서리 같은 아바타 위치 규칙이 여기 걸려요",
  "Background rail element with absolute positioning, background color, border radius and transition animation styles": "바탕 레일 요소. absolute 자리잡기, 바탕색, 모서리, 전환이 여기 걸려요",
  "Background rail element with border-top style and other divider connection line styles": "바탕 레일 요소. 위쪽 선 같은 구분선 연결 규칙이 여기 걸려요",
  "Body cell element with relative positioning, padding, word-wrap and other basic data cell styles": "본문 셀 요소. relative 위치 지정, 안쪽 여백, 줄바꿈 같은 데이터 셀의 기본 규칙이 여기 걸려요",
  "Body element that wraps Sider children layout and display styles": "본문 요소. Sider 의 자식들을 감싸는 배치와 표시 규칙이 여기 걸려요",
  "Body element with content area background color, padding and other content display styles": "본문 요소. 내용 영역의 바탕색과 안쪽 여백이 여기 걸려요",
  "Body element with flex ratio, minimum size, padding, overflow scroll and other content area display and layout styles": "본문 요소. flex 비율, 최소 크기, 안쪽 여백, 넘칠 때 스크롤 같은 내용 영역의 표시와 배치가 여기 걸려요",
  "Body element with list main area container styles and layout control": "본문 요소. 목록 본문 영역의 상자 규칙과 배치가 여기 걸려요",
  "Body element with padding and layout control for the calendar table that contains the calendar grid": "본문 요소. 달력 격자를 담는 표의 안쪽 여백과 배치가 여기 걸려요",
  "Body element with padding, color, background color and other styles for panel content area display": "본문 요소. 패널 내용 영역의 안쪽 여백·색·바탕색이 여기 걸려요",
  "Body element with tab panel container layout, animation and size control styles": "본문 요소. 탭 패널 상자의 배치·움직임·크기가 여기 걸려요",
  "Body element, set progress bar layout and size styles": "본문 요소. 진행 막대의 배치와 크기가 여기 걸려요",
  "Body row element with hover effects, selected states, expanded states and other interactive row styles": "본문 행 요소. 마우스 올림, 고름, 펼침 같은 상태별 행 반응이 여기 걸려요",
  "Body wrapper element with table body layout and container styles": "본문 감싸개 요소. 표 본문의 배치와 상자 규칙이 여기 걸려요",
  "Card bottom action area with padding, text right alignment, border radius, flex layout and other bottom container styles": "카드 아래쪽 동작 영역. 안쪽 여백, 오른쪽 정렬, 모서리, flex 배치 같은 아래쪽 상자 규칙이 여기 걸려요",
  "Card bottom action group with flex layout, list-style reset, background, top border and bottom border-radius for action buttons container": "카드 아래쪽 동작 그룹. flex 배치, 목록 표시 초기화, 바탕, 위쪽 선, 아래쪽 모서리가 여기 걸려요",
  "Card content area with padding, font-size and other content display styles": "카드 내용 영역. 안쪽 여백과 글자 크기가 여기 걸려요",
  "Card cover area with text center alignment, padding, image width and other image display styles": "카드 덮개 영역. 가운데 정렬, 안쪽 여백, 이미지 너비가 여기 걸려요",
  "Card extra operation area in top-right corner with text color and layout styles for additional content": "카드 오른쪽 위의 덧붙임 조작 영역. 글자색과 배치가 여기 걸려요",
  "Card header area with flex layout, min-height, padding, text color, font-weight, font-size, background, bottom border and top border-radius": "카드 머리 영역. flex 배치, 최소 높이, 안쪽 여백, 글자색, 글자 굵기, 글자 크기, 바탕, 아래쪽 선, 위쪽 모서리가 여기 걸려요",
  "Card header area with padding, width calculation, word break and other header container styles": "카드 머리 영역. 안쪽 여백, 너비 계산, 낱말 끊기가 여기 걸려요",
  "Card main content area with text alignment, border radius, box shadow, relative positioning, background color, border, background clip and other card styles": "카드 본문 영역. 글 정렬, 모서리, 그림자, relative 자리잡기, 바탕색, 선, 바탕 자르기 같은 카드 규칙이 여기 걸려요",
  "Card root element with positioning, background, border, border-radius, box-shadow, padding and other container styles": "카드 뿌리 요소. 자리잡기, 바탕, 선, 모서리, 그림자, 안쪽 여백 같은 상자 규칙이 여기 걸려요",
  "Card title with inline-block display, flex-grow, text ellipsis and other title display styles": "카드 제목. inline-block 표시, flex 늘림, 말줄임 같은 제목 표시 규칙이 여기 걸려요",
  "Checkbox icon element with size, direction, background, border, border-radius, transitions, and checked state checkmark styles": "체크박스 아이콘 요소. 크기·방향·바탕·선·모서리·전환, 그리고 켠 상태의 체크 표시가 여기 걸려요",
  "Close button element with absolute positioning, size, color, hover state and other interactive feedback styles": "닫기 버튼 요소. absolute 자리잡기, 크기, 색, 마우스 올림 같은 반응이 여기 걸려요",
  "Close button element, set position, size and interaction styles": "닫기 버튼 요소. 위치, 크기, 반응이 여기 걸려요",
  "Close element with close button layout, cursor styles, transition animations and other interaction styles": "닫기 요소. 닫기 버튼의 배치, 커서, 전환 같은 반응이 여기 걸려요",
  "Color block container with background color, border styles": "색 덩어리 상자. 바탕색과 선이 여기 걸려요",
  "Color block element with actual selected color styles": "색 덩어리 요소. 실제로 고른 색이 여기 걸려요",
  "Container element with clear-fix, max-width, scrollbar background and other table wrapper styles": "담는 상자 요소. clear-fix, 최대 너비, 스크롤 막대 바탕 같은 표 감싸개 규칙이 여기 걸려요",
  "Content element that wraps button text with typography styles including nowrap, text-align center, and Chinese character spacing optimization": "내용 요소. 버튼 글자를 감싸며 줄바꿈 없음, 가운데 정렬, 한자 자간 같은 활자 규칙이 여기 걸려요",
  "Content element with block display, overflow hidden, border radius, height, padding, transition animations and other switch content area layout and styles": "내용 요소. block 표시, 넘침 숨김, 모서리, 높이, 안쪽 여백, 전환 같은 스위치 내용 영역의 배치와 모양이 여기 걸려요",
  "Content element with button text content font size, color, alignment, line wrap and other text display styles": "내용 요소. 버튼 글의 글자 크기·색·정렬·줄바꿈 같은 표시 규칙이 여기 걸려요",
  "Content element with flex layout controlling content area typography and minimum width": "내용 요소. flex 배치로 내용 영역의 활자와 최소 너비를 잡아요",
  "Content element with form content area layout, styling and control container related styles": "내용 요소. 폼 내용 영역의 배치와 모양, 컨트롤 상자 관련 규칙이 여기 걸려요",
  "Content element with inline-block display, padding and other divider text content styles": "내용 요소. inline-block 표시와 안쪽 여백 같은 구분선 글자 규칙이 여기 걸려요",
  "Content element with layout and alignment styles for the prefix, value and suffix area": "내용 요소. 앞 장식·값·뒤 장식 영역의 배치와 정렬이 여기 걸려요",
  "Content element with margin, padding, background color and other content area styles": "내용 요소. 바깥 여백, 안쪽 여백, 바탕색이 여기 걸려요",
  "Content element with min width and height, padding, color, text alignment, background color, border radius, shadow and border styles": "내용 요소. 최소 너비와 높이, 안쪽 여백, 색, 글 정렬, 바탕색, 모서리, 그림자, 선이 여기 걸려요",
  "Content element with single tab panel layout, padding and other content display styles": "내용 요소. 탭 패널 하나의 배치와 안쪽 여백이 여기 걸려요",
  "Content element with table cell layout, color, font size, line height, word break and other content display styles": "내용 요소. 표 셀의 배치·색·글자 크기·줄 높이·낱말 끊기가 여기 걸려요",
  "Content element with table content area styling and layout": "내용 요소. 표 내용 영역의 모양과 배치가 여기 걸려요",
  "Content element with text content color, font styles and other content area styles": "내용 요소. 글 내용의 색과 글꼴이 여기 걸려요",
  "Content element with width, height and table styling control for the calendar table": "내용 요소. 달력 표의 너비·높이와 표 모양이 여기 걸려요",
  "Content element, set content text styles and layout": "내용 요소. 내용 글의 모양과 배치가 여기 걸려요",
  "Content section element that contains title and description": "제목과 설명을 담는 내용 구역 요소",
  "Cover element, set absolute positioning, z-index, background color and loading state overlay styles": "덮개 요소. absolute 자리잡기, z-index, 바탕색 같은 불러오는 중 덮개 규칙이 여기 걸려요",
  "Description element with font-size and line-height styles for additional content": "설명 요소. 덧붙는 내용의 글자 크기와 줄 높이가 여기 걸려요",
  "Description element, set content text styles and layout": "설명 요소. 내용 글의 모양과 배치가 여기 걸려요",
  "Description element, set font size, color and margin styles": "설명 요소. 글자 크기, 색, 바깥 여백이 여기 걸려요",
  "Description element, sets text color styles": "설명 요소. 글자색이 여기 걸려요",
  "Description text content with font styles and color": "설명 글 내용. 글꼴과 색이 여기 걸려요",
  "Drag control element with absolute positioning, user selection, z-index, center alignment, background color, hover and active states styles": "끌기 조작 요소. absolute 자리잡기, 글 선택, z-index, 가운데 정렬, 바탕색, 마우스 올림·누름 상태가 여기 걸려요",
  "Dragger element used to resize the drawer, with absolute positioning, transparent background, pointer events control, hover state styles, and dragging state styles": "서랍 크기를 바꾸는 끌기 핸들. absolute 위치 지정, 투명한 바탕, 포인터 이벤트, 마우스 올림 상태, 끄는 중 상태가 여기 걸려요",
  "Drawer container element with flex layout, width/height, overflow control, background color, pointer events and other drawer body styles": "서랍 상자 요소. flex 배치, 너비/높이, 넘침 제어, 바탕색, 포인터 이벤트 같은 서랍 본문 규칙이 여기 걸려요",
  "Extra content element with left margin, color, font size and other styles for additional operation area": "덧붙임 내용 요소. 왼쪽 바깥 여백, 색, 글자 크기 같은 덧붙임 조작 영역 규칙이 여기 걸려요",
  "Extra element with flex fixed layout and other additional operation content style controls": "덧붙임 요소. flex 고정 배치 같은 덧붙임 조작 내용 규칙이 여기 걸려요",
  "Extra prompt container element with spacing, color, and typography styles for supplementary text": "덧붙임 안내 상자 요소. 보충 글의 간격·색·활자가 여기 걸려요",
  "File item element with padding, background color, border styles, hover effects, status colors, transition animations and other styles": "파일 항목 요소. 안쪽 여백, 바탕색, 선, 마우스 올림 반응, 상태색, 전환이 여기 걸려요",
  "File list container with layout arrangement, transition animations, spacing control and other styles": "파일 목록 상자. 늘어놓기, 전환, 간격 조절이 여기 걸려요",
  "Footer element with bottom operation area styles and layout": "바닥 요소. 아래쪽 조작 영역의 모양과 배치가 여기 걸려요",
  "Footer element with flex shrink, padding, top border and other bottom operation area styles": "바닥 요소. flex 줄임, 안쪽 여백, 위쪽 선 같은 아래쪽 조작 영역 규칙이 여기 걸려요",
  "Footer element with footer background color, padding, top border, border-radius and other footer area styles": "바닥 요소. 바닥 바탕색, 안쪽 여백, 위쪽 선, 모서리가 여기 걸려요",
  "Footer element with table footer background color, text color and other footer styles": "바닥 요소. 표 바닥의 바탕색과 글자색이 여기 걸려요",
  "Footer element, sets top margin and action button styles": "바닥 요소. 위쪽 바깥 여백과 동작 버튼 모양이 여기 걸려요",
  "Group header element, with sticky positioning and background color": "그룹 머리 요소. 붙어 있는 위치 지정과 바탕색이 여기 걸려요",
  "Guide description text with padding, word wrap and other description text styles": "안내 설명 글. 안쪽 여백과 낱말 끊기 같은 설명 글 규칙이 여기 걸려요",
  "Guide title text with font weight and other title text styles": "안내 제목 글. 글자 굵기 같은 제목 글 규칙이 여기 걸려요",
  "Header cell element with relative positioning, padding, word-wrap, background, text color, font-weight and other header cell styles": "머리 셀 요소. relative 위치 지정, 안쪽 여백, 낱말 끊기, 바탕, 글자색, 글자 굵기가 여기 걸려요",
  "Header element with bottom padding and title area layout styles": "머리 요소. 아래쪽 안쪽 여백과 제목 영역 배치가 여기 걸려요",
  "Header element with flex layout, alignment, bottom margin and other layout and style controls for header area": "머리 요소. flex 배치, 정렬, 아래쪽 바깥 여백 같은 머리 영역의 배치와 모양이 여기 걸려요",
  "Header element with flex layout, alignment, height, padding, color, background color, bottom border, border radius and other header area styles": "머리 요소. flex 배치, 정렬, 높이, 안쪽 여백, 색, 바탕색, 아래쪽 선, 모서리가 여기 걸려요",
  "Header element with flex layout, alignment, padding, font size, line height, bottom border and other header area styles": "머리 요소. flex 배치, 정렬, 안쪽 여백, 글자 크기, 줄 높이, 아래쪽 선이 여기 걸려요",
  "Header element with flex layout, padding, color, line-height, cursor style, transition animations and other interactive styles for panel headers": "머리 요소. flex 배치, 안쪽 여백, 색, 줄 높이, 커서, 전환 같은 패널 머리의 반응이 여기 걸려요",
  "Header element with layout and style control for year selector, month selector and mode switcher": "머리 요소. 연 고르기·월 고르기·모드 전환의 배치와 모양이 여기 걸려요",
  "Header element with padding, bottom border and other header area styles": "머리 요소. 안쪽 여백과 아래쪽 선 같은 머리 영역 규칙이 여기 걸려요",
  "Header element with tab navigation header layout, background, borders and other styles": "머리 요소. 탭 내비게이션 머리의 배치·바탕·선이 여기 걸려요",
  "Header element with table cell, padding, vertical alignment and other avatar placeholder area layout styles": "머리 요소. 표 셀, 안쪽 여백, 세로 정렬 같은 아바타 위치 영역의 배치가 여기 걸려요",
  "Header row element with table header row layout and styling": "머리 행 요소. 표 머리 행의 배치와 모양이 여기 걸려요",
  "Header wrapper element with table header layout and container styles": "머리 감싸개 요소. 표 머리의 배치와 상자 규칙이 여기 걸려요",
  "Help container element with spacing, motion, and presentation styles for help and validation areas": "도움말 상자 요소. 도움말과 검증 영역의 간격·움직임·표시가 여기 걸려요",
  "Icon area of dropdown option, sets icon size and spacing styles": "드롭다운 항목의 아이콘 영역. 아이콘 크기와 간격이 여기 걸려요",
  "Icon element with border radius, transition animations, border styles, hover states, focus states and other interactive styles": "아이콘 요소. 모서리, 전환, 선, 마우스 올림, 초점 같은 반응이 여기 걸려요",
  "Icon element with button icon size, color, line height, alignment and other icon display styles": "아이콘 요소. 버튼 아이콘의 크기·색·줄 높이·정렬이 여기 걸려요",
  "Icon element with color, line-height, and margin styles, supporting different status icon types": "아이콘 요소. 색, 줄 높이, 바깥 여백이 여기 걸리고 상태별 아이콘을 받아요",
  "Icon element with font size, color, cursor style, transition animations and other icon display styles": "아이콘 요소. 글자 크기, 색, 커서, 전환이 여기 걸려요",
  "Icon element with font size, transition animations, rotation transforms and other styles and animations for expand/collapse arrows": "아이콘 요소. 글자 크기, 전환, 회전 같은 펼침/접힘 화살표의 모양과 움직임이 여기 걸려요",
  "Icon element with font-size, color inheritance, and SVG style reset for proper icon display": "아이콘 요소. 글자 크기, 색 상속, SVG 초기화가 여기 걸려요",
  "Icon element with icon size, color and text spacing styles": "아이콘 요소. 아이콘 크기, 색, 글자와의 간격이 여기 걸려요",
  "Icon element with margin, text alignment, font size, status colors and other icon styles": "아이콘 요소. 바깥 여백, 글 정렬, 글자 크기, 상태색이 여기 걸려요",
  "Icon element with min-width, font-size, transitions, icon reset styles, and spacing control with text": "아이콘 요소. 최소 너비, 글자 크기, 전환, 아이콘 초기화, 글자와의 간격이 여기 걸려요",
  "Icon element with tree node icon styles, size and state display": "아이콘 요소. 트리 마디 아이콘의 모양·크기·상태 표시가 여기 걸려요",
  "Icon element, set absolute positioning, font size, line height and status color styles": "아이콘 요소. absolute 자리잡기, 글자 크기, 줄 높이, 상태색이 여기 걸려요",
  "Icon element, set font size, line height and status color styles": "아이콘 요소. 글자 크기, 줄 높이, 상태색이 여기 걸려요",
  "Icon element, set the confirmation icon size, color and layout styles": "아이콘 요소. 확인 아이콘의 크기·색·배치가 여기 걸려요",
  "Image element, sets height, opacity, margin and image styles": "이미지 요소. 높이, 불투명도, 바깥 여백, 이미지 모양이 여기 걸려요",
  "Image element, sets width, height and vertical alignment styles": "이미지 요소. 너비, 높이, 세로 정렬이 여기 걸려요",
  "Image hover display prompt element, sets absolute positioning, background color, opacity and transition animation styles": "이미지에 마우스를 올렸을 때 뜨는 안내 요소. absolute 자리잡기, 바탕색, 불투명도, 전환이 여기 걸려요",
  "Indicator element with absolute positioning, width, height, background color, border radius, shadow, transition animations and other switch handle styles and interactive effects": "표시자 요소. absolute 위치 지정, 너비, 높이, 바탕색, 모서리, 그림자, 전환 같은 스위치 핸들의 모양과 반응이 여기 걸려요",
  "Indicator element with indicator bar color, position, dimensions, transitions and other active state indication styles": "표시자 요소. 표시 막대의 색·위치·크기·전환 같은 활성 상태 표시가 여기 걸려요",
  "Indicator element with positioning, z-index, dimensions, colors, fonts, text alignment, background, border-radius, box-shadow, and transition animations for complete badge styling": "표시자 요소. 자리잡기, z-index, 크기, 색, 글꼴, 글 정렬, 바탕, 모서리, 그림자, 전환이 모두 여기 걸려요",
  "Indicator element with width, height, background color, position changes, transition animations and other styles": "표시자 요소. 너비, 높이, 바탕색, 위치 이동, 전환이 여기 걸려요",
  "Indicator element, set percentage text or icon position and font styles": "표시자 요소. 퍼센트 글이나 아이콘의 위치와 글꼴이 여기 걸려요",
  "Indicator group container with inline-block display and other indicator container styles": "표시자 그룹 상자. inline-block 표시 같은 표시자 상자 규칙이 여기 걸려요",
  "Individual action button element including copy, edit, expand, collapse button styles like padding, border radius, colors, etc.": "동작 버튼 하나. 복사·편집·펼침·접힘 버튼의 안쪽 여백, 모서리, 색 따위가 여기 걸려요",
  "Individual dropdown option element, sets interaction states and background styles": "드롭다운 항목 하나. 상태별 반응과 바탕이 여기 걸려요",
  "Input element with text input, search, selected value display and other input core interaction styles": "입력 요소. 글 입력, 검색, 고른 값 표시 같은 입력의 핵심 반응이 여기 걸려요",
  "Input element, sets font, line height, text input and interaction styles": "입력 요소. 글꼴, 줄 높이, 글 입력과 반응이 여기 걸려요",
  "Item content element with height, overflow and other style control for custom content area inside calendar cells": "항목 내용 요소. 달력 셀 안에 직접 넣은 내용 영역의 높이와 넘침이 여기 걸려요",
  "Item content element with layout and typography styles for menu item content": "항목 내용 요소. 메뉴 항목 내용의 배치와 활자가 여기 걸려요",
  "Item content element with node detail content relative positioning, top offset, left margin, text color, word break and other content styles": "항목 내용 요소. 마디 상세 내용의 relative 위치 지정, 위쪽 치우침, 왼쪽 바깥 여백, 글자색, 낱말 끊기가 여기 걸려요",
  "Item element with background, border, hover state, selected state and other interactive styles for calendar cells": "항목 요소. 달력 셀의 바탕, 선, 마우스 올림, 고름 같은 상태별 반응이 여기 걸려요",
  "Item element with relative positioning, block display, margins, whitespace handling, cursor styles, transitions and other basic interactive styles for menu items": "항목 요소. relative 자리잡기, block 표시, 바깥 여백, 공백 처리, 커서, 전환 같은 메뉴 항목의 기본 반응이 여기 걸려요",
  "Item element with relative positioning, padding, colors, text ellipsis, border-radius, transitions and other tab item styles and interactive effects": "항목 요소. relative 자리잡기, 안쪽 여백, 색, 말줄임, 모서리, 전환 같은 탭 항목의 모양과 반응이 여기 걸려요",
  "Item element with single timeline node relative positioning, margin, padding, font size, finish state, color theme, layout direction and other node basic styles": "항목 요소. 타임라인 마디 하나의 relative 자리잡기, 바깥 여백, 안쪽 여백, 글자 크기, 완료 상태, 색, 배치 방향 같은 기본 규칙이 여기 걸려요",
  "Item element with text color, link color transitions, hover effects, padding, border-radius, height, and margin styles": "항목 요소. 글자색, 링크 색 전환, 마우스 올림 반응, 안쪽 여백, 모서리, 높이, 바깥 여백이 여기 걸려요",
  "Item element with tree node base styles, drag state, role attributes, indentation, switcher, content wrapper and other node structure": "항목 요소. 트리 마디의 기본 모양, 끄는 중 상태, role 속성, 들여쓰기, 펼침 버튼, 내용 감싸개 같은 마디 구조가 여기 걸려요",
  "Item element, set size, padding, border, background color, hover state and active state styles": "항목 요소. 크기, 안쪽 여백, 선, 바탕색, 마우스 올림·누름 상태가 여기 걸려요",
  "Item element, sets absolute positioning, width calculation, transition animation and masonry item styles": "항목 요소. absolute 자리잡기, 너비 계산, 전환 같은 masonry 항목 규칙이 여기 걸려요",
  "Item element, with padding, split line and hover background": "항목 요소. 안쪽 여백, 구분선, 마우스 올림 바탕이 여기 걸려요",
  "Item header element with header area layout containing title and rail, alignment, text direction and other styles": "항목 머리 요소. 제목과 레일을 담는 머리 영역의 배치·정렬·글 방향이 여기 걸려요",
  "Item icon element with node head icon absolute positioning, width/height size, background color, border, border radius, wave animation and other icon styles": "항목 아이콘 요소. 마디 머리 아이콘의 absolute 자리잡기, 너비/높이, 바탕색, 선, 모서리, 물결 움직임이 여기 걸려요",
  "Item rail element with timeline node connection track line absolute positioning, top offset, left offset, height, border color, width, style and other connection line styles": "항목 레일 요소. 타임라인 마디를 연결하는 선의 absolute 위치 지정, 위쪽 치우침, 왼쪽 치우침, 높이, 선 색·굵기·종류가 여기 걸려요",
  "Item section element with section container containing header and content flex layout, wrap, gap and other layout styles": "항목 구역 요소. 머리와 내용을 담는 구역 상자의 flex 배치, 줄바꿈, 간격이 여기 걸려요",
  "Item title element (no effect in horizontal mode) with title text styles and layout": "항목 제목 요소 (가로 모드에서는 안 걸려요). 제목 글의 모양과 배치가 여기 걸려요",
  "Item title element with node title text font size, line height, color and other text styles": "항목 제목 요소. 마디 제목 글의 글자 크기, 줄 높이, 색이 여기 걸려요",
  "Item wrapper element with timeline node content wrapping container styles": "항목 감싸개 요소. 타임라인 마디 내용을 감싸는 상자 규칙이 여기 걸려요",
  "Label content element with min height, line height, padding, text ellipsis and content layout styles": "라벨 내용 요소. 최소 높이, 줄 높이, 안쪽 여백, 말줄임, 내용 배치가 여기 걸려요",
  "Label element with color, font weight, font size, line height, text align, colon styles and other label text styles": "라벨 요소. 색, 글자 굵기, 글자 크기, 줄 높이, 글 정렬, 콜론 모양 같은 라벨 글 규칙이 여기 걸려요",
  "Label element with flex layout, overflow hidden, whitespace nowrap, text alignment, vertical alignment, plus label color, font size, height, required marks and other label display styles": "라벨 요소. flex 배치, 넘침 숨김, 줄바꿈 없음, 글 정렬, 세로 정렬에 더해 라벨 색·글자 크기·높이·필수 표시가 여기 걸려요",
  "Label element with padding, text color, disabled states, alignment and other text styles": "라벨 요소. 안쪽 여백, 글자색, 못 쓰는 상태, 정렬 같은 글 규칙이 여기 걸려요",
  "Label text element with padding and spacing styles relative to the checkbox": "라벨 글 요소. 체크박스와의 안쪽 여백과 간격이 여기 걸려요",
  "Link item element with padding, text color, hover states, transition animations and other styles": "링크 항목 요소. 안쪽 여백, 글자색, 마우스 올림 상태, 전환이 여기 걸려요",
  "List element with list content styles, layout and scroll control": "목록 요소. 목록 내용의 모양, 배치, 스크롤이 여기 걸려요",
  "List item content element with text ellipsis, padding and other list item text content display styles": "목록 항목 내용 요소. 말줄임, 안쪽 여백 같은 목록 항목 글 표시 규칙이 여기 걸려요",
  "List item element with relative positioning, padding, border, hover state, selected state, disabled state and other list item interaction styles": "목록 항목 요소. relative 자리잡기, 안쪽 여백, 선, 마우스 올림·고름·못 씀 같은 상태별 반응이 여기 걸려요",
  "List item icon element with checkbox and other icon styles and interaction states": "목록 항목 아이콘 요소. 체크박스 같은 아이콘의 모양과 상태가 여기 걸려요",
  "Main content area of dropdown option, sets content layout and link styles": "드롭다운 항목의 본문 영역. 내용 배치와 링크 모양이 여기 걸려요",
  "Mask element with absolute positioning, z-index, background color, pointer events and other mask layer styles and interaction controls": "막 요소. absolute 자리잡기, z-index, 바탕색, 포인터 이벤트 같은 막 층의 모양과 조작 제어가 여기 걸려요",
  "Mask element with fixed positioning, z-index, background color, animation transitions and other mask layer styles": "막 요소. fixed 자리잡기, z-index, 바탕색, 전환 같은 막 층 규칙이 여기 걸려요",
  "Mask layer element with fixed positioning, full screen coverage, z-index, pointer events, transition animation and other mask styles": "막 층 요소. fixed 자리잡기, 화면 전체 덮기, z-index, 포인터 이벤트, 전환이 여기 걸려요",
  "Menu list element (no effect in horizontal mode) with menu list layout and container styles": "메뉴 목록 요소 (가로 모드에서는 안 걸려요). 메뉴 목록의 배치와 상자 규칙이 여기 걸려요",
  "Message item root element, set background color, border radius, shadow, padding and animation styles": "메시지 항목의 뿌리 요소. 바탕색, 모서리, 그림자, 안쪽 여백, 움직임이 여기 걸려요",
  "Message list content element, set notice layout, gap and height transition styles": "메시지 목록의 내용 요소. 알림 배치, 간격, 높이 전환이 여기 걸려요",
  "Message list root element, set positioning, z-index, width, scroll area and placement styles": "메시지 목록의 뿌리 요소. 위치 지정, z-index, 너비, 스크롤 영역, 놓일 위치가 여기 걸려요",
  "Modal container element with relative positioning, background, background-clip, border, border-radius, box-shadow, pointer-events, padding and other modal body styles": "Modal 상자 요소. relative 자리잡기, 바탕, 바탕 자르기, 선, 모서리, 그림자, 포인터 이벤트, 안쪽 여백 같은 창 본문 규칙이 여기 걸려요",
  "Multi-segment track container element with absolute positioning and transition animation styles": "여러 구간 트랙 상자 요소. absolute 자리잡기와 전환이 여기 걸려요",
  "Notice root element, set background color, border radius, shadow, padding and animation styles": "알림의 뿌리 요소. 바탕색, 모서리, 그림자, 안쪽 여백, 움직임이 여기 걸려요",
  "Notification list content element, set notice layout, gap and height transition styles": "알림 목록의 내용 요소. 알림 배치, 간격, 높이 전환이 여기 걸려요",
  "Notification list root element, set positioning, z-index, width, scroll area and placement styles": "알림 목록의 뿌리 요소. 위치 지정, z-index, 너비, 스크롤 영역, 놓일 위치가 여기 걸려요",
  "Option element with relative positioning, text alignment, cursor style, transition, selected state background and hover styles": "고를 항목 요소. relative 자리잡기, 글 정렬, 커서, 전환, 고른 상태의 바탕, 마우스 올림 모양이 여기 걸려요",
  "Pagination item element with pagination item styling and interactive effects": "Pagination 항목 요소. 쪽 항목의 모양과 반응이 여기 걸려요",
  "Pagination root element with pagination component basic styles and layout": "Pagination 뿌리 요소. 컴포넌트의 기본 모양과 배치가 여기 걸려요",
  "Panel element with flex basis, grow ratio and panel container styles": "패널 요소. flex 기준 크기, 늘림 비율, 패널 상자 규칙이 여기 걸려요",
  "Paragraph element with padding, list item styles, background color, border radius and other paragraph placeholder styles": "문단 요소. 안쪽 여백, 목록 항목 모양, 배경색, 모서리 같은 문단 스타일 규칙 적용",
  "Popup body element with container layout and styles for date panel table": "팝업 본문 요소. 날짜 패널 표의 상자 배치와 모양 적용",
  "Popup element with dropdown tree selection panel positioning, z-index, background, border, shadow and other popup layer styles": "팝업 요소. 드롭다운 트리 선택 패널의 위치 지정, z-index, 배경, 선, 그림자 같은 팝업 레이어 규칙 적용",
  "Popup element, set absolute positioning, z-index, background color, border radius, shadow and dropdown options styles": "팝업 요소. absolute 자리잡기, z-index, 바탕색, 모서리, 그림자, 드롭다운 항목 모양이 여기 걸려요",
  "Popup header element with navigation buttons, month/year selectors and other header control area layout and styles": "팝업 머리 요소. 이동 버튼, 월·연 고르개 같은 머리 조작 영역의 배치와 모양이 여기 걸려요",
  "Popup item element with tree node option styles, hover state, selected state and other interaction states": "팝업 항목 요소. 트리 마디 항목의 모양과 마우스 올림·고름 같은 상태별 반응이 여기 걸려요",
  "Popup menu element (no effect in inline mode) with popup layer positioning, z-index, background and other styles": "팝업 메뉴 요소 (inline 모드에서는 안 걸려요). 팝업 층의 자리잡기, z-index, 바탕이 여기 걸려요",
  "Popup menu element with dropdown absolute positioning, z-index, display control, max-height, scrolling and other styles": "팝업 메뉴 요소. 드롭다운의 absolute 자리잡기, z-index, 표시 제어, 최대 높이, 스크롤이 여기 걸려요",
  "Popup panel root container with background color, shadow effects, color selection panel, slider controls and preset colors": "팝업 패널의 루트 요소. 배경색, 그림자, 색상 선택 패널, 슬라이더, 사전 정의된 색상 포함",
  "Popup switcher element with tree node expand/collapse button styles and background": "팝업 펼침 버튼 요소. 트리 노드를 펼치고 접는 버튼의 모양과 배경 적용",
  "Popup title element with tree node title text display styles": "팝업 제목 요소. 트리 마디 제목 글의 표시 규칙이 여기 걸려요",
  "Prefix element with inline-block display, right margin and other prefix content layout styles": "앞 장식 요소. inline-block 표시, 오른쪽 바깥 여백 같은 앞 내용 배치가 여기 걸려요",
  "Prefix element with prefix content layout and styles": "앞 장식 요소. 앞에 붙는 내용의 배치와 모양이 여기 걸려요",
  "Prefix wrapper element, sets flex layout, alignment and right margin styles": "앞 장식 감싸개 요소. flex 배치, 정렬, 오른쪽 바깥 여백이 여기 걸려요",
  "Preview actions group element, sets flex layout, background color, border radius and action button styles": "미리보기 동작 그룹 요소. flex 배치, 배경색, 모서리, 동작 버튼 모양 적용",
  "Preview body element, sets flex layout, center alignment and pointer event styles": "미리보기 본문 요소. flex 배치, 가운데 정렬, 포인터 이벤트가 여기 걸려요",
  "Preview footer element, sets absolute positioning, center layout and bottom operation area styles": "미리보기 바닥 요소. absolute 자리잡기, 가운데 배치, 아래쪽 조작 영역이 여기 걸려요",
  "Preview mask element, sets absolute positioning and semi-transparent background styles": "미리보기 막 요소. absolute 자리잡기와 반투명 바탕이 여기 걸려요",
  "Preview root element, sets fixed positioning, z-index and background mask styles": "미리보기 뿌리 요소. fixed 자리잡기, z-index, 바탕 막이 여기 걸려요",
  "Progress element, set progress styles for auto-closing notifications": "진행 요소. 저절로 닫히는 알림의 진행 표시가 여기 걸려요",
  "Rail element, set background track color and border radius styles. Not exist in steps mode": "레일 요소. 트랙 바탕색과 모서리가 여기 걸려요. steps 모드에는 없어요",
  "Remove button element with editable tab close button size, color, hover state and other interactive feedback styles": "지우기 버튼 요소. 고칠 수 있는 탭의 닫기 버튼 크기·색·마우스 올림 반응이 여기 걸려요",
  "Root container element with layout styles, disabled text color, user-select control, cursor styles and other basic styles": "뿌리 상자 요소. 배치, 못 쓰는 상태의 글자색, 글 선택 제어, 커서 같은 기본 규칙이 여기 걸려요",
  "Root element (including arrows, content elements) with absolute positioning, z-index, block display, max width, visibility, transform origin and arrow background color": "뿌리 요소 (화살표와 내용 요소를 포함). absolute 자리잡기, z-index, block 표시, 최대 너비, 보임 여부, 변형 기준점, 화살표 바탕색이 여기 걸려요",
  "Root element containing background, border, border-radius and overall layout structure of the calendar component": "뿌리 요소. 달력 컴포넌트의 바탕, 선, 모서리, 전체 배치 구조가 여기 걸려요",
  "Root element of dropdown, sets positioning, z-index and container styles": "드롭다운의 뿌리 요소. 자리잡기, z-index, 상자 규칙이 여기 걸려요",
  "Root element with Sider layout, theme, width and collapsed state styles": "뿌리 요소. Sider 의 배치, 테마, 너비, 접힘 상태가 여기 걸려요",
  "Root element with base typography styles, layout, and positioning": "뿌리 요소. 기본 활자, 배치, 자리잡기가 여기 걸려요",
  "Root element with basic menu container styles and layout": "뿌리 요소. 메뉴 상자의 기본 모양과 배치가 여기 걸려요",
  "Root element with basic styles, reset styles, border styles, layout direction and other overall styles for description list container": "뿌리 요소. 기본 모양, 초기화, 선, 배치 방향 같은 설명 목록 상자의 전체 규칙이 여기 걸려요",
  "Root element with basic tab container styles, layout and direction control": "뿌리 요소. 탭 상자의 기본 모양, 배치, 방향 제어가 여기 걸려요",
  "Root element with border, background, padding, border-radius, and positioning styles for the alert container": "뿌리 요소. alert 상자의 선, 바탕, 안쪽 여백, 모서리, 자리잡기가 여기 걸려요",
  "Root element with border, border-radius, background color and container styles that control the overall layout and appearance of collapse panels": "루트 요소. 접힘 패널 전체의 배치와 스타일을 결정하는 선, 모서리, 배경색 적용",
  "Root element with border-top style, divider styling and other basic divider container styles": "뿌리 요소. 위쪽 선 같은 구분선 상자의 기본 규칙이 여기 걸려요",
  "Root element with comprehensive button styling including border, background, padding, border-radius, box-shadow, transitions, cursor, font-weight, alignment, and layout properties": "뿌리 요소. 선, 바탕, 안쪽 여백, 모서리, 그림자, 전환, 커서, 글자 굵기, 정렬 같은 버튼의 모양 전체가 여기 걸려요",
  "Root element with fixed positioning, z-index control, pointer events, color and other basic styles and layout control for drawer container": "뿌리 요소. fixed 자리잡기, z-index 제어, 포인터 이벤트, 색 같은 서랍 상자의 기본 규칙과 배치가 여기 걸려요",
  "Root element with flex layout, gap settings, alignment, wrap and other spacing container basic styles": "뿌리 요소. flex 배치, 간격, 정렬, 줄바꿈 같은 간격 상자의 기본 규칙이 여기 걸려요",
  "Root element with flex layout, nowrap, alignment, CSS variables and other basic step container styles": "뿌리 요소. flex 배치, 줄바꿈 없음, 정렬, CSS 변수 같은 단계 상자의 기본 규칙이 여기 걸려요",
  "Root element with flex layout, transfer container base styles and layout control": "뿌리 요소. flex 배치와 옮기기 상자의 기본 모양·배치가 여기 걸려요",
  "Root element with flex layout, width and height, alignment and stretch styles": "뿌리 요소. flex 배치, 너비와 높이, 정렬, 늘림이 여기 걸려요",
  "Root element with float button base styles, shape size, type theme, fixed positioning, z-index, shadow, spacing and other container styles": "뿌리 요소. 떠 있는 버튼의 기본 모양, 크기, 종류별 테마, fixed 자리잡기, z-index, 그림자, 간격이 여기 걸려요",
  "Root element with font-size, background, border-radius, scrollbar-color and other basic table container styles": "뿌리 요소. 글자 크기, 바탕, 모서리, 스크롤 막대 색 같은 표 상자의 기본 규칙이 여기 걸려요",
  "Root element with form item margin-bottom, vertical-align, transitions, hidden states, error/warning states and other basic form item container styles": "뿌리 요소. 폼 항목의 아래쪽 바깥 여백, 세로 정렬, 전환, 숨김·오류·경고 상태 같은 폼 항목 상자의 기본 규칙이 여기 걸려요",
  "Root element with inline-block display, auto height, padding, font size, line height, nowrap, background color, border, border radius, opacity, transition animations, text alignment, relative positioning and other basic tag styles": "뿌리 요소. inline-block 표시, 자동 높이, 안쪽 여백, 글자 크기, 줄 높이, 줄바꿈 없음, 바탕색, 선, 모서리, 불투명도, 전환, 글 정렬, relative 자리잡기 같은 태그의 기본 규칙이 여기 걸려요",
  "Root element with inline-block layout, padding, background, border radius, transition and container styles": "뿌리 요소. inline-block 배치, 안쪽 여백, 바탕, 모서리, 전환, 상자 규칙이 여기 걸려요",
  "Root element with inline-flex layout, baseline alignment, cursor style, reset styles and other basic checkbox container styles": "뿌리 요소. inline-flex 배치, baseline 정렬, 커서, 초기화 같은 체크박스 상자의 기본 규칙이 여기 걸려요",
  "Root element with layout positioning, padding, margin, background color and other basic styles": "뿌리 요소. 배치와 자리잡기, 안쪽 여백, 바깥 여백, 바탕색 같은 기본 규칙이 여기 걸려요",
  "Root element with layout styles, cursor styles, disabled text color and other basic container styles": "뿌리 요소. 배치, 커서, 못 쓰는 상태의 글자색 같은 기본 상자 규칙이 여기 걸려요",
  "Root element with min-width, height, line-height, vertical alignment, background color, border, border radius, cursor style, transition animations, user selection and other basic switch container styles": "뿌리 요소. 최소 너비, 높이, 줄 높이, 세로 정렬, 바탕색, 선, 모서리, 커서, 전환, 글 선택 같은 스위치 상자의 기본 규칙이 여기 걸려요",
  "Root element with relative positioning, height, margin, padding, cursor style and touch action control": "뿌리 요소. relative 자리잡기, 높이, 바깥 여백, 안쪽 여백, 커서, 터치 동작 제어가 여기 걸려요",
  "Root element with relative positioning, inline-block display, and fit-content width for basic layout": "뿌리 요소. relative 자리잡기, inline-block 표시, 내용에 맞춘 너비가 여기 걸려요",
  "Root element with relative positioning, top position, width, max-width, margins, bottom padding and other basic layout styles for modal container": "뿌리 요소. relative 자리잡기, 위쪽 위치, 너비, 최대 너비, 바깥 여백, 아래쪽 안쪽 여백 같은 창 상자의 기본 배치가 여기 걸려요",
  "Root element with reset styles and overall container styles for statistic component": "뿌리 요소. 초기화와 통계 컴포넌트의 상자 규칙이 여기 걸려요",
  "Root element with table display, width, animation effects, border radius and other skeleton container basic styles": "뿌리 요소. table 표시, 너비, 움직임, 모서리 같은 스켈레톤 상자의 기본 규칙이 여기 걸려요",
  "Root element with text alignment, layout styles and other basic container styles": "뿌리 요소. 글 정렬과 배치 같은 기본 상자 규칙이 여기 걸려요",
  "Root element with text color, font size, icon size and other basic styles, using flex layout with ordered list": "뿌리 요소. 글자색, 글자 크기, 아이콘 크기 같은 기본 규칙이 여기 걸리고, 순서 있는 목록에 flex 배치를 써요",
  "Root element with timeline container list style reset, vertical layout, dot icon, outlined style, alternate layout and other basic container styles": "뿌리 요소. 타임라인 상자의 목록 표시 초기화, 세로 배치, 점 아이콘, 테두리형, 번갈아 배치 같은 기본 규칙이 여기 걸려요",
  "Root element with tree control base styles, layout and container control": "뿌리 요소. 트리 컨트롤의 기본 모양, 배치, 상자 제어가 여기 걸려요",
  "Root element with tree selector base styles, border, border radius container styles": "뿌리 요소. 트리 선택칸의 기본 모양, 선, 모서리가 여기 걸려요",
  "Root element, set flex layout, alignment, flex wrap and list styles": "뿌리 요소. flex 배치, 정렬, 줄바꿈, 목록 모양이 여기 걸려요",
  "Root element, set flex layout, padding, background color, border, border radius and relative positioning styles": "뿌리 요소. flex 배치, 안쪽 여백, 바탕색, 선, 모서리, relative 자리잡기가 여기 걸려요",
  "Root element, set inline flex layout, relative positioning, padding and border styles": "뿌리 요소. inline-flex 배치, relative 자리잡기, 안쪽 여백, 선이 여기 걸려요",
  "Root element, set relative positioning and basic container styles": "뿌리 요소. relative 자리잡기와 기본 상자 규칙이 여기 걸려요",
  "Root element, sets inline-block layout, width, border radius and reset styles": "뿌리 요소. inline-block 배치, 너비, 모서리, 초기화가 여기 걸려요",
  "Root element, sets relative positioning and inline-block layout styles": "뿌리 요소. relative 자리잡기와 inline-block 배치가 여기 걸려요",
  "Root element, sets relative positioning, flex layout and masonry container styles": "뿌리 요소. relative 자리잡기, flex 배치, masonry 상자 규칙이 여기 걸려요",
  "Root element, sets text alignment, font and line height styles": "뿌리 요소. 글 정렬, 글꼴, 줄 높이가 여기 걸려요",
  "Root element, the scroll container, with font and relative positioning": "뿌리 요소. 굴러가는 상자이고 글꼴과 relative 자리잡기가 여기 걸려요",
  "Section element with flex layout, width, height, min height, border, border radius and other single-side transfer container styles": "구역 요소. flex 배치, 너비, 높이, 최소 높이, 선, 모서리 같은 한쪽 옮기기 상자의 규칙이 여기 걸려요",
  "Section element with skeleton content area layout styles": "구역 요소. 스켈레톤 내용 영역의 배치가 여기 걸려요",
  "Separator element with divider styling": "구분자 요소. 구분선 모양이 여기 걸려요",
  "Separator element with margin and color styles for the divider": "구분자 요소. 구분선의 바깥 여백과 색이 여기 걸려요",
  "Single action button element, sets button styling, hover effects and click interactions": "동작 버튼 하나. 버튼 모양, 마우스 올림 반응, 누름 반응이 여기 걸려요",
  "Single help message item with typography styles for prompt, error, and warning text": "도움말 항목 하나. 안내·오류·경고 글의 활자가 여기 걸려요",
  "Single indicator element with width/height size, inline-block display, border radius, background color, right margin, active state and other dot styles": "표시자 하나. 너비·높이, inline-block 표시, 모서리, 바탕색, 오른쪽 바깥 여백, 활성 상태 같은 점 규칙이 여기 걸려요",
  "Slider handle control element with absolute positioning, size, outline, user selection, background color, border shadow, border radius, cursor style and transition animation": "슬라이더 핸들 요소. absolute 위치 지정, 크기, 외곽선, 텍스트 선택, 배경색, 그림자, 모서리, 커서, 트랜지션 적용",
  "Source body element, only applies to left list body styles": "원본 본문 요소. 왼쪽 목록 본문에만 걸려요",
  "Source footer element, only applies to left footer area styles": "원본 바닥 요소. 왼쪽 바닥 영역에만 걸려요",
  "Source header element, only applies to left header area styles": "원본 머리 요소. 왼쪽 머리 영역에만 걸려요",
  "Source item content element, only applies to left text content styles": "원본 항목 내용 요소. 왼쪽 글 내용에만 걸려요",
  "Source item element, only applies to left list item styles": "원본 항목 요소. 왼쪽 목록 항목에만 걸려요",
  "Source item icon element, only applies to left icon styles": "원본 항목 아이콘 요소. 왼쪽 아이콘에만 걸려요",
  "Source list element, only applies to left list content styles": "원본 목록 요소. 왼쪽 목록 내용에만 걸려요",
  "Source section element, only applies to left transfer section container styles": "원본 구역 요소. 왼쪽 옮기기 구역 상자에만 걸려요",
  "Source title element, only applies to left title text styles": "원본 제목 요소. 왼쪽 제목 글에만 걸려요",
  "Step item content element with color, font-size, line-height, word-break, transitions and other content text styles": "단계 항목의 콘텐츠 요소. 색상, 글자 크기, 줄 높이, 줄바꿈, 트랜지션 같은 텍스트 스타일 규칙 적용",
  "Step item element with flex layout, relative positioning and other basic step item container styles": "단계 항목 요소. flex 배치, relative 자리잡기 같은 단계 항목 상자의 기본 규칙이 여기 걸려요",
  "Step item header element with flex layout, nowrap, alignment and other header area layout styles": "단계 항목의 머리 요소. flex 배치, 줄바꿈 없음, 정렬 같은 머리 영역 배치가 여기 걸려요",
  "Step item icon element with icon size, positioning, font-size and other icon display related styles": "단계 항목의 아이콘 요소. 아이콘 크기, 자리잡기, 글자 크기가 여기 걸려요",
  "Step item rail element with border-style, border-width, transitions and other connecting line styles": "단계 항목의 레일 요소. 선 종류, 선 굵기, 트랜지션 같은 연결선 규칙 적용",
  "Step item section element with step content area layout and styling": "단계 항목의 구역 요소. 단계 내용 영역의 배치와 모양이 여기 걸려요",
  "Step item subtitle element with color, font-weight, font-size, line-height, margin, word-break and other subtitle styles": "단계 항목의 부제목 요소. 색상, 글자 굵기, 글자 크기, 줄 높이, 바깥 여백, 줄바꿈 적용",
  "Step item title element with color, font-size, line-height, word-break, transitions and other title text styles": "단계 항목의 제목 요소. 색상, 글자 크기, 줄 높이, 줄바꿈, 트랜지션 같은 제목 텍스트 스타일 규칙 적용",
  "Step item wrapper element with flex layout, nowrap, top padding and other step content wrapping styles": "단계 항목의 감싸개 요소. flex 배치, 줄바꿈 없음, 위쪽 안쪽 여백 같은 단계 내용 감싸기 규칙이 여기 걸려요",
  "Submenu item content element with submenu content layout and typography": "하위 메뉴 항목의 내용 요소. 하위 메뉴 내용의 배치와 활자가 여기 걸려요",
  "Submenu item element with submenu item styles and interactive effects": "하위 메뉴 항목 요소. 하위 메뉴 항목의 모양과 반응이 여기 걸려요",
  "Submenu item icon element with submenu icon size and styles": "하위 메뉴 항목의 아이콘 요소. 하위 메뉴 아이콘의 크기와 모양이 여기 걸려요",
  "Submenu list element with submenu list layout and container styles": "하위 메뉴 목록 요소. 하위 메뉴 목록의 배치와 상자 규칙이 여기 걸려요",
  "Submenu title element with submenu title styles and interactive effects": "하위 메뉴 제목 요소. 하위 메뉴 제목의 모양과 반응이 여기 걸려요",
  "Subtitle element with font size, text color, line height and other text styles": "부제목 요소. 글자 크기, 글자색, 줄 높이가 여기 걸려요",
  "Suffix element with inline-block display, left margin and other suffix content layout styles": "뒤 장식 요소. inline-block 표시, 왼쪽 바깥 여백 같은 뒤 내용 배치가 여기 걸려요",
  "Suffix element with layout and styling for suffix content like clear button, etc.": "뒤 장식 요소. 지우기 버튼처럼 뒤에 붙는 내용의 배치와 모양이 여기 걸려요",
  "Suffix element with suffix content, clear button, dropdown arrow and other suffix area styles": "뒤 장식 요소. 뒤에 붙는 내용, 지우기 버튼, 드롭다운 화살표 같은 뒤 영역 규칙이 여기 걸려요",
  "Suffix wrapper element, sets flex layout, margin and transition animation styles": "뒤 장식 감싸개 요소. flex 배치, 바깥 여백, 전환이 여기 걸려요",
  "Switcher element with tree node expand/collapse button styles and background": "펼침 버튼 요소. 트리 노드를 펼치고 접는 버튼의 모양과 배경 적용",
  "Target body element, only applies to right list body styles": "대상 본문 요소. 오른쪽 목록 본문에만 걸려요",
  "Target footer element, only applies to right footer area styles": "대상 바닥 요소. 오른쪽 바닥 영역에만 걸려요",
  "Target header element, only applies to right header area styles": "대상 머리 요소. 오른쪽 머리 영역에만 걸려요",
  "Target item content element, only applies to right text content styles": "대상 항목 내용 요소. 오른쪽 글 내용에만 걸려요",
  "Target item element, only applies to right list item styles": "대상 항목 요소. 오른쪽 목록 항목에만 걸려요",
  "Target item icon element, only applies to right icon styles": "대상 항목 아이콘 요소. 오른쪽 아이콘에만 걸려요",
  "Target list element, only applies to right list content styles": "대상 목록 요소. 오른쪽 목록 내용에만 걸려요",
  "Target section element, only applies to right transfer section container styles": "대상 구역 요소. 오른쪽 옮기기 구역 상자에만 걸려요",
  "Target title element, only applies to right title text styles": "대상 제목 요소. 오른쪽 제목 글에만 걸려요",
  "TextArea element in editable mode, used to customize className and inline styles for the edit input": "고치는 중일 때의 TextArea 요소. 입력칸의 className 과 인라인 스타일을 여기서 정해요",
  "Textarea element, set font, line height, text input and background styles": "Textarea 요소. 글꼴, 줄 높이, 글 입력, 바탕이 여기 걸려요",
  "The container element that holds the child elements wrapped by Spin, setting opacity and transition animation": "Spin 이 감싼 자식들을 담는 상자 요소. 불투명도와 전환이 여기 걸려요",
  "The description element, which sets font size and line height": "설명 요소. 글자 크기와 줄 높이가 여기 걸려요",
  "The indicator element, which sets width, height, font size, inline-block display, transition animation, transform origin, and line height": "표시자 요소. 너비, 높이, 글자 크기, inline-block 표시, 전환, 변형 기준점, 줄 높이가 여기 걸려요",
  "The loading element area, which sets relative positioning, flexbox layout, alignment, and color": "불러오는 중 영역 요소. relative 자리잡기, flex 배치, 정렬, 색이 여기 걸려요",
  "The root element, which sets absolute positioning, display control, color, font size, text alignment, vertical alignment, opacity, and transition animation (only effective when fullscreen is false)": "뿌리 요소. absolute 자리잡기, 표시 제어, 색, 글자 크기, 글 정렬, 세로 정렬, 불투명도, 전환이 여기 걸려요 (fullscreen 이 거짓일 때만 걸려요)",
  "Title content area of dropdown option, sets layout and text styles": "드롭다운 항목의 제목 영역. 배치와 글 모양이 여기 걸려요",
  "Title cover with styles for cover image display and layout": "제목 덮개. 덮개 이미지의 표시와 배치가 여기 걸려요",
  "Title element with flex auto layout and margin styles for title text layout and typography": "제목 요소. flex auto 배치와 바깥 여백 같은 제목 글의 배치·활자가 여기 걸려요",
  "Title element with flex ratio, margin, font weight, font size, line height and other title text styles": "제목 요소. flex 비율, 바깥 여백, 글자 굵기, 글자 크기, 줄 높이가 여기 걸려요",
  "Title element with font size, text color, line height, text alignment and other text styles": "제목 요소. 글자 크기, 글자색, 줄 높이, 글 정렬이 여기 걸려요",
  "Title element with margin, color, font-weight, font-size, line-height, word-wrap and other title text styles": "제목 요소. 바깥 여백, 색, 글자 굵기, 글자 크기, 줄 높이, 줄바꿈이 여기 걸려요",
  "Title element with table title styling and layout": "제목 요소. 표 제목의 모양과 배치가 여기 걸려요",
  "Title element with text color and font styling for the alert title": "제목 요소. alert 제목의 글자색과 글꼴이 여기 걸려요",
  "Title element with text color, font size and other title text display styles": "제목 요소. 글자색, 글자 크기 같은 제목 글 표시 규칙이 여기 걸려요",
  "Title element with text ellipsis, flex ratio, color, font weight, font size, line height and other title text styles": "제목 요소. 말줄임, flex 비율, 색, 글자 굵기, 글자 크기, 줄 높이가 여기 걸려요",
  "Title element with text ellipsis, flex ratio, text alignment, auto left margin and other title text layout and styles": "제목 요소. 말줄임, flex 비율, 글 정렬, 왼쪽 자동 여백 같은 제목 글 배치가 여기 걸려요",
  "Title element with tree node title text display styles and text content": "제목 요소. 트리 마디 제목 글의 표시 규칙과 글 내용이 여기 걸려요",
  "Title element with width, height, background color, border radius and other title placeholder styles": "제목 요소. 너비, 높이, 배경색, 모서리 같은 제목 스타일 규칙 적용",
  "Title element, set color, font size, line height and margin styles": "제목 요소. 색, 글자 크기, 줄 높이, 바깥 여백이 여기 걸려요",
  "Title element, set text color, font size, line height and content display styles": "제목 요소. 글자색, 글자 크기, 줄 높이, 내용 표시가 여기 걸려요",
  "Title text element with font styles, color changes, text decoration, transition effects and other styles": "제목 글 요소. 글꼴, 색 바뀜, 밑줄, 전환이 여기 걸려요",
  "Tour root container with absolute positioning, z-index control, max width, visibility, arrow background color variable, theme styles and other container styles": "Tour 의 뿌리 상자. absolute 자리잡기, z-index 제어, 최대 너비, 보임 여부, 화살표 바탕색 변수, 테마가 여기 걸려요",
  "Track element, set progress fill color and transition animation styles": "트랙 요소. 진행이 채워지는 색과 전환이 여기 걸려요",
  "Track selection bar element with absolute positioning, background color, border radius and transition animation styles": "트랙에서 고른 구간 요소. absolute 자리잡기, 바탕색, 모서리, 전환이 여기 걸려요",
  "Trigger container with border styles, transition animations, size controls, displaying color block and text content": "여는 상자. 선, 전환, 크기 제어가 여기 걸리고 색 덩어리와 글 내용을 보여 줘요",
  "Upload button container with button styles, disabled state, visibility control and other styles": "올리기 버튼 상자. 버튼 모양, 못 쓰는 상태, 보임 제어가 여기 걸려요",
  "Value element with text color, font size, font family and other statistic number display styles": "값 요소. 글자색, 글자 크기, 글꼴 같은 통계 숫자 표시 규칙이 여기 걸려요",
  "Wrapped item element with spacing item layout and styles, providing wrapper for each child element for inline alignment": "감싸인 항목 요소. 간격 항목의 배치와 모양이 여기 걸리고, 자식마다 감싸개를 둬 한 줄 정렬을 도와요",
  "Wrapper element for icon and content with content layout styles": "아이콘과 내용을 감싸는 요소. 내용 배치가 여기 걸려요",
  "Wrapper element for icon and title, set content layout, gap and alignment styles": "아이콘과 제목을 감싸는 요소. 내용 배치, 간격, 정렬이 여기 걸려요",
  "Wrapper element used for motion container with animation and transition effect styles": "움직임 상자로 쓰는 감싸개 요소. 움직임과 전환이 여기 걸려요",
  "set `actions` of List.Item": "List.Item 의 `actions` 를 정해요",
  "set `extra` of List.Item": "List.Item 의 `extra` 를 정해요",
};
