export const KO_TOKENS: Record<string, string> = {
  "Preset motion curve.": "미리 정해 둔 움직임 곡선.",
  "The most widely used font size in the design system, from which the text gradient will be derived.": "디자인 시스템에서 가장 널리 쓰이는 글자 크기. 여기서 글자 계단이 파생돼요.",
  "Default text color which comply with W3C standards, and this color is also the darkest neutral color.": "W3C 기준을 지키는 기본 글자색. 중립색 중 가장 짙은 색이기도 해요.",
  "Line height of text.": "글자의 줄 높이.",
  "The font family of Ant Design prioritizes the default interface font of the system, and provides a set of alternative font libraries that are suitable for screen display to maintain the readability and readability of the font under different platforms and browsers, reflecting the friendly, stable and professional characteristics.": "Ant Design 의 글꼴 세트. 시스템 기본 인터페이스 글꼴을 먼저 쓰고, 화면 표시에 알맞은 대체 글꼴을 함께 둬요. 플랫폼과 브라우저가 달라도 읽기 쉬움을 지키려는 것이고, 친근하고 안정적이며 전문적인 인상을 노려요.",
  "Motion speed, medium speed. Used for medium element animation interaction.": "움직임 속도, 중간. 중간 크기 요소의 움직임에 써요.",
  "Border width of base components": "기본 컴포넌트의 선 굵기",
  "Motion speed, slow speed. Used for large element animation interaction.": "움직임 속도, 느림. 큰 요소의 움직임에 써요.",
  "Border style of base components": "기본 컴포넌트의 선 종류",
  "Control the margin of an element, with a small size.": "요소의 바깥 여백, 작은 크기.",
  "Control the extra small padding of the element.": "요소의 아주 작은 안쪽 여백.",
  "LG size border radius, used in some large border radius components, such as Card, Modal and other components.": "큰 모서리. Card · Modal 처럼 모서리가 큰 컴포넌트가 써요.",
  "Brand color is one of the most direct visual elements to reflect the characteristics and communication of the product. After you have selected the brand color, we will automatically generate a complete color palette and assign it effective design semantics.": "브랜드 색은 제품의 성격과 메시지를 가장 곧바로 드러내는 요소예요. 이 색을 정하면 나머지 팔레트가 자동으로 만들어지고 각자 의미를 갖게 돼요.",
  "Control the color of text in disabled state.": "못 쓰는 상태의 글자색.",
  "SM size border radius, used in small size components, such as Button, Input, Select and other input components in small size": "작은 모서리. small 크기의 Button · Input · Select 같은 입력 컴포넌트가 써요",
  "The stroke color under the main color gradient, used on the stroke of components such as Slider.": "주색 계조 중 선 색. Slider 같은 컴포넌트의 선에 써요.",
  "Large font size": "큰 글자 크기",
  "Control the width of the line when the component is in focus state.": "초점이 맞았을 때의 선 굵기.",
  "LG component height": "큰 컴포넌트 높이",
  "Container background color, e.g: default button, input box, etc. Be sure not to confuse this with `colorBgElevated`.": "담는 상자의 바탕색. default 버튼·입력칸 따위예요. `colorBgElevated` 와 헷갈리지 마세요.",
  "Used as the color of separator, this color is the same as colorBorderSecondary but with transparency.": "구분선 색. `colorBorderSecondary` 와 같은 색인데 투명도가 들어가 있어요.",
  "Border radius of base components": "기본 컴포넌트의 모서리",
  "Control the extra extra small padding of the element.": "요소의 아주아주 작은 안쪽 여백.",
  "Control the margin of an element, with the smallest size.": "요소의 바깥 여백, 가장 작은 크기.",
  "Control the padding of the element.": "요소의 안쪽 여백.",
  "Default border color, used to separate different elements, such as: form separator, card separator, etc.": "기본 선 색. 서로 다른 요소를 가르는 데 써요. 폼 구분선, 카드 구분선 따위.",
  "Used to represent the visual elements of the operation failure, such as the error Button, error Result component, etc.": "동작이 실패했음을 나타내는 색. error Button · error Result 따위가 써요.",
  "Weak action. Such as `allowClear` or Alert close button": "약한 동작. `allowClear` 나 Alert 닫기 버튼 같은 위치",
  "Control the small padding of the element.": "요소의 작은 안쪽 여백.",
  "Control the font color of heading.": "제목 글자색.",
  "The height of the basic controls such as buttons and input boxes in Ant Design": "버튼·입력칸 같은 기본 컨트롤의 높이",
  "Control the background color of container in disabled state.": "못 쓰는 상태일 때 담는 상자의 바탕색.",
  "Control the font weight of heading components (such as h1, h2, h3) or selected item.": "제목 컴포넌트(h1 · h2 · h3)나 고른 항목의 글자 굵기.",
  "Control the highlight color of text with background color, such as the text in Primary Button components.": "색이 깔린 바탕 위 글자의 색. Primary Button 의 글자 같은 자리예요.",
  "Line height of large text.": "큰 글자의 줄 높이.",
  "Control the font color of text description.": "설명 글의 글자색.",
  "Control the margin of an element, with a medium size.": "요소의 바깥 여백, 중간 크기.",
  "Used to represent the warning map token, such as Notification, Alert, etc. Alert or Control component(like Input) will use these map tokens.": "경고 계열의 map 토큰. Notification · Alert 따위가 쓰고, Alert 나 Input 같은 컨트롤도 이 토큰을 써요.",
  "Container background color of the popup layer, in dark mode the color value of this token will be a little brighter than `colorBgContainer`. E.g: modal, pop-up, menu, etc.": "떠 있는 층이 담는 상자의 바탕색. 다크 모드에서는 `colorBgContainer` 보다 조금 밝아요. 모달 · 팝업 · 메뉴 따위예요.",
  "Control the font size of operation icon in Select, Cascader, etc. Normally same as fontSizeSM.": "Select · Cascader 따위의 조작 아이콘 글자 크기. 보통 `fontSizeSM` 과 같아요.",
  "Small font size": "작은 글자 크기",
  "Control the background color of control component item when hovering.": "컨트롤 항목에 마우스를 올렸을 때의 바탕색.",
  "Control the large padding of the element.": "요소의 큰 안쪽 여백.",
  "Hover state under the main color gradient.": "주색 계조 중 마우스를 올렸을 때.",
  "SM component height": "작은 컴포넌트 높이",
  "The default line width of the outline class components, such as Button, Input, Select, etc.": "테두리형 컴포넌트의 기본 선 굵기. Button · Input · Select 따위요.",
  "The second level of fill color can outline the shape of the element more clearly, such as Rate, Skeleton, etc. It can also be used as the Hover state of the third level of fill color, such as Table, etc.": "2단계 채움색. 요소의 윤곽이 더 또렷해져요. Rate · Skeleton 따위. Table 처럼 3단계의 hover 로도 써요.",
  "XS size border radius, used in some small border radius components, such as Segmented, Arrow and other components with small border radius.": "아주 작은 모서리. Segmented · Arrow 처럼 모서리가 작은 컴포넌트가 써요.",
  "Control the margin of an element, with a medium-small size.": "요소의 바깥 여백, 중간보다 작은 크기.",
  "Control the secondary box shadow style of an element.": "요소의 보조 그림자.",
  "The background color of the error state.": "error 상태의 바탕색.",
  "The third level of fill color is used to outline the shape of the element, such as Slider, Segmented, etc. If there is no emphasis requirement, it is recommended to use the third level of fill color as the default fill color.": "3단계 채움색. 요소의 윤곽을 잡아 줘요. Slider · Segmented 따위. 특별히 강조할 일이 없으면 이걸 기본 채움색으로 쓰길 권해요.",
  "Weak action hover color. Such as `allowClear` or Alert close button": "약한 동작에 마우스를 올렸을 때의 색. `allowClear` 나 Alert 닫기 버튼 같은 위치",
  "Control the border color of the element in the disabled state.": "못 쓰는 상태일 때 요소의 선 색.",
  "Control the color of placeholder text.": "플레이스홀더 글자의 색.",
  "The fourth level of text color is the lightest text color, such as form input prompt text, disabled color text, etc.": "4단계 글자색. 가장 옅은 글자색이에요. 폼 입력 안내 글, 못 쓰는 상태의 글 따위.",
  "Used to represent the token sequence of operation success, such as Result, Progress and other components will use these map tokens.": "동작 성공을 나타내는 토큰 계열. Result · Progress 따위가 이 map 토큰을 써요.",
  "Control the background color of text in hover state.": "마우스를 올렸을 때 글자의 바탕색.",
  "Motion speed, fast speed. Used for small element animation interaction.": "움직임 속도, 빠름. 작은 요소의 움직임에 써요.",
  "Pure white color don't changed by theme": "테마를 타지 않는 순백색",
  "The background color of the warning state.": "warning 상태의 바탕색.",
  "The default state of the text in the error color.": "error 색 글자의 기본 상태.",
  "Active border color": "누르고 있을 때의 선 색",
  "Hover border color": "마우스를 올렸을 때의 선 색",
  "Control the background color of control component item when active.": "컨트롤 항목을 누르고 있을 때의 바탕색.",
  "Control the color of form control prefix/suffix in error state.": "error 상태일 때 폼 컨트롤 앞뒤 장식의 색.",
  "Control the color of form control prefix/suffix in warning state.": "warning 상태일 때 폼 컨트롤 앞뒤 장식의 색.",
  "Control the margin of an element, with a large size.": "요소의 바깥 여백, 큰 크기.",
  "The default state of the text in the warning color.": "warning 색 글자의 기본 상태.",
  "The hover state background color of the error state.": "error 상태에 마우스를 올렸을 때의 바탕색.",
  "The hover state background color of the warning state.": "warning 상태에 마우스를 올렸을 때의 바탕색.",
  "The hover state border color of the error state.": "error 상태에 마우스를 올렸을 때의 선 색.",
  "The size of the component arrow": "컴포넌트 화살표의 크기",
  "The weakest level of fill color is suitable for color blocks that are not easy to attract attention, such as zebra stripes, color blocks that distinguish boundaries, etc.": "가장 약한 채움색. 눈에 띄지 않아도 되는 색 덩어리에 알맞아요. 얼룩말 줄무늬, 경계를 나누는 색 덩어리 따위.",
  "Background color of addon": "덧붙임 영역의 바탕색",
  "Background color when the input box hovers": "입력칸에 마우스를 올렸을 때의 바탕색",
  "Background color when the input box is activated": "입력칸이 활성일 때의 바탕색",
  "Box-shadow when active": "활성일 때의 그림자",
  "Box-shadow when active in error status": "error 상태에서 활성일 때의 그림자",
  "Box-shadow when active in warning status": "warning 상태에서 활성일 때의 그림자",
  "Control the alternative background color of element.": "요소의 대체 바탕색.",
  "Control the background color of text in active state.": "누르고 있을 때 글자의 바탕색.",
  "Control the horizontal padding of an element.": "요소의 좌우 안쪽 여백.",
  "Control the interactive size of control component.": "컨트롤 컴포넌트의 조작 크기.",
  "Control the outline width of input component.": "입력 컴포넌트의 외곽선 굵기.",
  "Font size": "글자 크기",
  "Font size of large": "큰 글자 크기",
  "Font size of small": "작은 글자 크기",
  "Horizontal padding of input": "입력칸의 좌우 안쪽 여백",
  "Horizontal padding of large input": "큰 입력칸의 좌우 안쪽 여백",
  "Horizontal padding of small input": "작은 입력칸의 좌우 안쪽 여백",
  "The background color of the mask, used to cover the content below the mask, Modal, Drawer, Image and other components use this token": "막의 바탕색. 아래 내용을 덮는 데 써요. Modal · Drawer · Image 따위가 이 토큰을 써요",
  "Used to represent the operation information of the Token sequence, such as Alert, Tag, Progress, and other components use these map tokens.": "동작 안내를 나타내는 토큰 계열. Alert · Tag · Progress 따위가 이 map 토큰을 써요.",
  "Vertical padding of input": "입력칸의 위아래 안쪽 여백",
  "Vertical padding of large input": "큰 입력칸의 위아래 안쪽 여백",
  "Vertical padding of small input": "작은 입력칸의 위아래 안쪽 여백",
  "Background color of multiple selector when disabled": "여럿 고르기 선택칸이 못 쓰는 상태일 때의 바탕색",
  "Background color of multiple tag": "여럿 고르기 태그의 바탕색",
  "Border color of multiple tag": "여럿 고르기 태그의 선 색",
  "Border color of multiple tag when disabled": "여럿 고르기 태그가 못 쓰는 상태일 때의 선 색",
  "Control the background color of control component item when hovering and active.": "컨트롤 항목에 마우스를 올린 채 누르고 있을 때의 바탕색.",
  "Control the color of hyperlink when clicked.": "누른 링크의 색.",
  "Control the color of hyperlink when hovering.": "마우스를 올린 링크의 색.",
  "Control the color of hyperlink.": "링크 색.",
  "Control the margin of an element, with the largest size.": "요소의 바깥 여백, 가장 큰 크기.",
  "Control the tertiary box shadow style of an element.": "요소의 3차 그림자.",
  "Height of multiple tag": "여럿 고르기 태그의 높이",
  "Height of multiple tag with large size": "큰 크기 여럿 고르기 태그의 높이",
  "Height of multiple tag with small size": "작은 크기 여럿 고르기 태그의 높이",
  "Text color of multiple tag when disabled": "여럿 고르기 태그가 못 쓰는 상태일 때의 글자색",
  "The hover state border color of the warning state.": "warning 상태에 마우스를 올렸을 때의 선 색.",
  "The second level of text color is generally used in scenarios where text color is not emphasized, such as label text, menu text selection state, etc.": "2단계 글자색. 글자를 강조하지 않는 위치에 주로 써요. 라벨 글자, 메뉴 선택 상태 글자 따위.",
  "The third level of text color is generally used for descriptive text, such as form supplementary explanation text, list descriptive text, etc.": "3단계 글자색. 설명 글에 주로 써요. 폼 보충 설명, 목록 설명 글 따위.",
  "Base zIndex of component like FloatButton, Affix which can be cover by large popup": "FloatButton · Affix 처럼 큰 팝업에 덮여도 되는 컴포넌트의 기준 z-index",
  "Control the box shadow style of an element.": "요소의 그림자.",
  "Control the margin of an element, with an extra-large size.": "요소의 바깥 여백, 아주 큰 크기.",
  "Control the opacity of the loading state.": "불러오는 중 상태의 불투명도.",
  "Control the outline color of input component.": "입력 컴포넌트의 외곽선 색.",
  "Control the text decoration style of a link on focus.": "초점이 맞았을 때 링크의 밑줄 모양.",
  "Control the text decoration style of a link on mouse hover.": "마우스를 올렸을 때 링크의 밑줄 모양.",
  "Control the text decoration style of a link.": "링크의 밑줄 모양.",
  "Dark active state under the main color gradient.": "주색 계조 중 누르고 있을 때의 짙은 색.",
  "Slightly lighter than the default border color, this color is the same as `colorSplit`. Solid color is used.": "기본 선 색보다 살짝 옅어요. `colorSplit` 과 같은 색이고 불투명한 색을 써요.",
  "Text color when option is selected": "고른 항목의 글자색",
  "The hover state of the error color.": "error 색에 마우스를 올렸을 때.",
  "z-index of dropdown": "드롭다운의 z-index",
  "z-index of popup": "팝업의 z-index",
  "Active outline color": "활성일 때의 외곽선 색",
  "Background color of cell hover state": "셀에 마우스를 올렸을 때의 바탕색",
  "Background color of cell in range": "범위 안 셀의 바탕색",
  "Background color of clear button": "지우기 버튼의 바탕색",
  "Background color of disabled cell": "못 쓰는 셀의 바탕색",
  "Background color of footer": "바닥 영역의 바탕색",
  "Background color of header": "머리 영역의 바탕색",
  "Background color of hovered cell in range": "범위 안에서 마우스를 올린 셀의 바탕색",
  "Background color of hovered node": "마우스를 올린 마디의 바탕색",
  "Background color of selected node": "고른 마디의 바탕색",
  "Background color of selector": "선택칸의 바탕색",
  "Background color when option is active": "고를 항목이 활성일 때의 바탕색",
  "Background color when option is selected": "고를 항목을 골랐을 때의 바탕색",
  "Background of active danger menu item in dark mode": "다크 모드에서 활성인 danger 메뉴 항목의 바탕",
  "Border color of cell in range when picking": "범위를 고르는 중일 때 범위 안 셀의 선 색",
  "Border color of default button": "default 버튼의 선 색",
  "Bottom padding of item": "항목의 아래쪽 안쪽 여백",
  "Control the background color of control component item when active and disabled.": "컨트롤 항목이 활성이면서 못 쓰는 상태일 때의 바탕색.",
  "Control the extra large padding of the element.": "요소의 아주 큰 안쪽 여백.",
  "Control the horizontal padding of content element, suitable for large screen devices.": "내용 요소의 좌우 안쪽 여백. 큰 화면에 알맞아요.",
  "Control the maximum width of small screens.": "작은 화면의 최대 너비.",
  "Control the medium padding of the element.": "요소의 중간 안쪽 여백.",
  "Control the outline color of input component in error state.": "error 상태일 때 입력 컴포넌트의 외곽선 색.",
  "Control the outline color of input component in warning state.": "warning 상태일 때 입력 컴포넌트의 외곽선 색.",
  "Control the screen width of small screens.": "작은 화면의 화면 너비.",
  "Font size of h2 tag.": "h2 태그의 글자 크기.",
  "Font size of h3 tag.": "h3 태그의 글자 크기.",
  "Font size of h5 tag.": "h5 태그의 글자 크기.",
  "Font size of option": "고를 항목의 글자 크기",
  "Font size of title": "제목의 글자 크기",
  "Font weight when option is selected": "고른 항목의 글자 굵기",
  "Height of cell": "셀의 높이",
  "Height of cell text": "셀 글자의 높이",
  "Height of decade/year/quarter/month/week cell": "10년/연/분기/월/주 셀의 높이",
  "Height of header": "머리 영역의 높이",
  "Height of menu item": "메뉴 항목의 높이",
  "Height of option": "고를 항목의 높이",
  "Height of single selected item with large size": "큰 크기에서 하나 고른 항목의 높이",
  "Height of time cell": "시각 셀의 높이",
  "Height of time column": "시각 열의 높이",
  "Icon size": "아이콘 크기",
  "Indent width of tree": "트리의 들여쓰기 너비",
  "Inline end padding of arrow": "화살표의 끝쪽 안쪽 여백",
  "Light background color of primary color, usually used for weak visual level selection state.": "주색의 옅은 바탕색. 약하게 고른 상태에 주로 써요.",
  "Line height of h3 tag.": "h3 태그의 줄 높이.",
  "Line height of h5 tag.": "h5 태그의 줄 높이.",
  "Line height of option": "고를 항목의 줄 높이",
  "Line height of small text.": "작은 글자의 줄 높이.",
  "Margin bottom of title": "제목의 아래쪽 바깥 여백",
  "Max width of preset area": "미리 정해 둔 영역의 최대 너비",
  "Node title height": "마디 제목의 높이",
  "Padding of header": "머리 영역의 안쪽 여백",
  "Padding of option": "고를 항목의 안쪽 여백",
  "Size of dot": "점의 크기",
  "Size of icon": "아이콘의 크기",
  "Solid background color, currently only used for the default solid button background color.": "solid 바탕색. 지금은 default solid 버튼의 바탕에만 써요.",
  "Switcher width of tree": "트리의 펼침 버튼 너비",
  "Text color of extra area": "덧붙임 영역의 글자색",
  "Text color of hovered node": "마우스를 올린 마디의 글자색",
  "Text color of selected node": "고른 마디의 글자색",
  "The darkest fill color is used to distinguish between the second and third level of fill color, and is currently only used in the hover effect of Slider.": "가장 진한 채움색. 2·3단계 채움색과 구별하려고 두었고 지금은 Slider 의 hover 에만 써요.",
  "The hover state color corresponding to the light background color of the primary color.": "주색의 옅은 바탕색에 마우스를 올렸을 때의 색.",
  "The hover state of the warning color.": "warning 색에 마우스를 올렸을 때.",
  "The wrong color fills the background color of the suspension state, which is currently only used in the hover effect of the dangerous filled button.": "error 색이 채우는 hover 상태의 바탕색. 지금은 danger filled 버튼의 hover 에만 써요.",
  "Title font size": "제목 글자 크기",
  "Width of cell": "셀의 너비",
  "Width of preset area": "미리 정해 둔 영역의 너비",
  "Width of time column": "시각 열의 너비",
  "Action button color": "동작 버튼의 색",
  "Active background color of handle": "핸들이 활성일 때의 바탕색",
  "Background Color of body": "본문의 바탕색",
  "Background Color of footer": "바닥 영역의 바탕색",
  "Background Color of header": "머리 영역의 바탕색",
  "Background Color of light theme sider": "라이트 테마 사이드바의 바탕색",
  "Background Color of light theme sider trigger": "라이트 테마 사이드바 여닫이의 바탕색",
  "Background Color of sider": "사이드바의 바탕색",
  "Background Color of sider trigger": "사이드바 여닫이의 바탕색",
  "Background color of Message": "Message 의 바탕색",
  "Background color of Notification progress bar": "Notification 진행 막대의 바탕색",
  "Background color of Pagination item": "Pagination 항목의 바탕색",
  "Background color of Pagination item link": "Pagination 항목 링크의 바탕색",
  "Background color of Radio button": "Radio 버튼의 바탕색",
  "Background color of Switch handle": "Switch 핸들의 바탕색",
  "Background color of active Pagination item": "활성인 Pagination 항목의 바탕색",
  "Background color of card actions": "카드 동작 영역의 바탕색",
  "Background color of card header": "카드 머리 영역의 바탕색",
  "Background color of card tab": "카드 탭의 바탕색",
  "Background color of checked Radio button": "고른 Radio 버튼의 바탕색",
  "Background color of checked and disabled Radio button": "고른 채로 못 쓰는 Radio 버튼의 바탕색",
  "Background color of checked solid Radio button text": "고른 solid Radio 버튼 글자의 바탕색",
  "Background color of checked solid Radio button text when active": "고른 solid Radio 버튼 글자를 누르고 있을 때의 바탕색",
  "Background color of checked solid Radio button text when hover": "고른 solid Radio 버튼 글자에 마우스를 올렸을 때의 바탕색",
  "Background color of content": "내용의 바탕색",
  "Background color of danger menu item when active": "danger 메뉴 항목을 누르고 있을 때의 바탕색",
  "Background color of default button": "default 버튼의 바탕색",
  "Background color of default button when active": "default 버튼을 누르고 있을 때의 바탕색",
  "Background color of default button when hover": "default 버튼에 마우스를 올렸을 때의 바탕색",
  "Background color of disabled active Pagination item": "못 쓰는 활성 Pagination 항목의 바탕색",
  "Background color of error notification container": "error 알림 상자의 바탕색",
  "Background color of fixed table header when sorted": "정렬된 고정 표 머리의 바탕색",
  "Background color of full calendar": "전체 달력의 바탕색",
  "Background color of full calendar panel": "전체 달력 패널의 바탕색",
  "Background color of ghost button": "ghost 버튼의 바탕색",
  "Background color of handle": "핸들의 바탕색",
  "Background color of handle in filled variant": "filled 변형에서 핸들의 바탕색",
  "Background color of horizontal menu item when hover": "가로 메뉴 항목에 마우스를 올렸을 때의 바탕색",
  "Background color of horizontal menu item when selected": "가로 메뉴 항목을 골랐을 때의 바탕색",
  "Background color of info notification container": "info 알림 상자의 바탕색",
  "Background color of input": "입력칸의 바탕색",
  "Background color of item when active": "항목을 누르고 있을 때의 바탕색",
  "Background color of item when hover": "항목에 마우스를 올렸을 때의 바탕색",
  "Background color of item when selected": "항목을 골랐을 때의 바탕색",
  "Background color of label": "라벨의 바탕색",
  "Background color of link button when hover": "link 버튼에 마우스를 올렸을 때의 바탕색",
  "Background color of menu item when active": "메뉴 항목을 누르고 있을 때의 바탕색",
  "Background color of menu item when hover": "메뉴 항목에 마우스를 올렸을 때의 바탕색",
  "Background color of menu item when selected": "메뉴 항목을 골랐을 때의 바탕색",
  "Background color of node": "마디의 바탕색",
  "Background color of popup": "팝업의 바탕색",
  "Background color of previous button in primary type": "primary 형태에서 이전 버튼의 바탕색",
  "Background color of rail": "레일의 바탕색",
  "Background color of rail when hover": "레일에 마우스를 올렸을 때의 바탕색",
  "Background color of selected danger menu item": "고른 danger 메뉴 항목의 바탕색",
  "Background color of selected date item": "고른 날짜 항목의 바탕색",
  "Background color of selected directory node": "고른 디렉터리 마디의 바탕색",
  "Background color of selected item": "고른 항목의 바탕색",
  "Background color of sub-menu item": "하위 메뉴 항목의 바탕색",
  "Background color of success notification container": "success 알림 상자의 바탕색",
  "Background color of table expanded row": "펼친 표 행의 바탕색",
  "Background color of table header filter button when hovered": "표 머리의 거르기 버튼에 마우스를 올렸을 때의 바탕색",
  "Background color of table header when sorted": "정렬된 표 머리의 바탕색",
  "Background color of table header when sorted and hovered": "정렬된 표 머리에 마우스를 올렸을 때의 바탕색",
  "Background color of table hovered row": "마우스를 올린 표 행의 바탕색",
  "Background color of table selected row": "고른 표 행의 바탕색",
  "Background color of table selected row when hovered": "고른 표 행에 마우스를 올렸을 때의 바탕색",
  "Background color of table sorted column": "정렬된 표 열의 바탕색",
  "Background color of text button when hover": "text 버튼에 마우스를 올렸을 때의 바탕색",
  "Background color of track": "트랙의 바탕색",
  "Background color of track when disabled": "못 쓰는 상태일 때 트랙의 바탕색",
  "Background color of track when hover": "트랙에 마우스를 올렸을 때의 바탕색",
  "Background color of warning notification container": "warning 알림 상자의 바탕색",
  "Background of Segmented container": "Segmented 상자의 바탕",
  "Background of active menu item in dark mode": "다크 모드에서 활성인 메뉴 항목의 바탕",
  "Background of content": "내용의 바탕",
  "Background of content in borderless style": "테두리 없는 형태에서 내용의 바탕",
  "Background of expand button": "펼침 버튼의 바탕",
  "Background of filter dropdown menu item": "거르기 드롭다운 메뉴 항목의 바탕",
  "Background of footer": "바닥 영역의 바탕",
  "Background of header": "머리 영역의 바탕",
  "Background of hovered danger menu item in dark mode": "다크 모드에서 마우스를 올린 danger 메뉴 항목의 바탕",
  "Background of hovered menu item in dark mode": "다크 모드에서 마우스를 올린 메뉴 항목의 바탕",
  "Background of menu item in dark mode": "다크 모드에서 메뉴 항목의 바탕",
  "Background of sticky scrollbar": "붙어 있는 스크롤 막대의 바탕",
  "Background of submenu item in dark mode": "다크 모드에서 하위 메뉴 항목의 바탕",
  "Background of table header": "표 머리의 바탕",
  "Base duration of loading animation": "불러오는 중 움직임의 기준 길이",
  "Border color of avatars in a group": "묶인 아바타들의 선 색",
  "Border color of default button when active": "default 버튼을 누르고 있을 때의 선 색",
  "Border color of default ghost button": "default ghost 버튼의 선 색",
  "Border color of dot": "점의 선 색",
  "Border color of dot when active": "점이 활성일 때의 선 색",
  "Border color of handle": "핸들의 선 색",
  "Border color of handle when active": "핸들이 활성일 때의 선 색",
  "Border color of information color.": "info 색의 선 색.",
  "Border color of success color, used for Tag and Alert success state border color": "success 색의 선 색. Tag 와 Alert 의 success 상태 선 색에 써요",
  "Border color of table": "표의 선 색",
  "Border radius of alert": "alert 의 모서리",
  "Border radius of horizontal menu item": "가로 메뉴 항목의 모서리",
  "Border radius of line progress bar": "선형 진행 막대의 모서리",
  "Border radius of skeleton": "스켈레톤의 모서리",
  "Border radius of sticky scrollbar": "붙어 있는 스크롤 막대의 모서리",
  "Border radius of table header": "표 머리의 모서리",
  "Border width of handle": "핸들의 선 굵기",
  "Border width of handle when hover": "핸들에 마우스를 올렸을 때의 선 굵기",
  "Border width of menu item active bar": "메뉴 항목 활성 막대의 선 굵기",
  "Border width of node": "마디의 선 굵기",
  "Bottom margin of title": "제목의 아래쪽 바깥 여백",
  "Close button size": "닫기 버튼 크기",
  "Code font, used for code, pre and kbd elements in Typography": "코드 글꼴. Typography 의 code · pre · kbd 요소에 써요",
  "Color of Radio button text": "Radio 버튼 글자의 색",
  "Color of arrow in nav": "내비게이션 화살표의 색",
  "Color of checked and disabled Radio button text": "고른 채로 못 쓰는 Radio 버튼 글자의 색",
  "Color of checked solid Radio button text": "고른 solid Radio 버튼 글자의 색",
  "Color of danger menu item text": "danger 메뉴 항목 글자의 색",
  "Color of danger menu item text in dark mode": "다크 모드에서 danger 메뉴 항목 글자의 색",
  "Color of disabled Radio dot": "못 쓰는 Radio 점의 색",
  "Color of disabled menu item in dark mode": "다크 모드에서 못 쓰는 메뉴 항목의 색",
  "Color of disabled menu item text": "못 쓰는 메뉴 항목 글자의 색",
  "Color of filter dropdown": "거르기 드롭다운의 색",
  "Color of footer text": "바닥 영역 글자의 색",
  "Color of group title text": "그룹 제목 글자의 색",
  "Color of group title text in dark mode": "다크 모드에서 그룹 제목 글자의 색",
  "Color of handle": "핸들의 색",
  "Color of handle when disabled": "못 쓰는 상태일 때 핸들의 색",
  "Color of hovered link": "마우스를 올린 링크의 색",
  "Color of hovered menu item in dark mode": "다크 모드에서 마우스를 올린 메뉴 항목의 색",
  "Color of hovered preview operation icon": "마우스를 올린 미리보기 조작 아이콘의 색",
  "Color of indicator": "표시자의 색",
  "Color of light theme sider trigger": "라이트 테마 사이드바 여닫이의 색",
  "Color of menu item text": "메뉴 항목 글자의 색",
  "Color of menu item text in dark mode": "다크 모드에서 메뉴 항목 글자의 색",
  "Color of preview operation icon": "미리보기 조작 아이콘의 색",
  "Color of remaining part of progress bar": "진행 막대에서 아직 안 찬 부분의 색",
  "Color of selected danger menu item in dark mode": "다크 모드에서 고른 danger 메뉴 항목의 색",
  "Color of selected danger menu item text": "고른 danger 메뉴 항목 글자의 색",
  "Color of selected horizontal menu item text": "고른 가로 메뉴 항목 글자의 색",
  "Color of selected menu item in dark mode": "다크 모드에서 고른 메뉴 항목의 색",
  "Color of selected menu item text": "고른 메뉴 항목 글자의 색",
  "Color of separator": "구분선의 색",
  "Color of sider trigger": "사이드바 여닫이의 색",
  "Color of submenu title when submenu has selected item": "하위 메뉴에 고른 항목이 있을 때 그 제목의 색",
  "Color of table header text": "표 머리 글자의 색",
  "Content font size": "내용 글자 크기",
  "Control image opacity": "이미지 불투명도",
  "Control the color of background border of element.": "요소의 바탕 테두리 색.",
  "Control the color of page element when highlighted.": "강조된 페이지 요소의 색.",
  "Control the font color of text label.": "라벨 글자의 색.",
  "Control the horizontal padding of an element with a small-medium size.": "요소의 좌우 안쪽 여백, 중간보다 조금 작은 크기.",
  "Control the maximum width of extra small screens.": "아주 작은 화면의 최대 너비.",
  "Control the maximum width of large screens.": "큰 화면의 최대 너비.",
  "Control the maximum width of medium screens.": "중간 화면의 최대 너비.",
  "Control the minimum width of XXXL screens.": "XXXL 화면의 최소 너비.",
  "Control the minimum width of extra extra large screens.": "아주아주 큰 화면의 최소 너비.",
  "Control the minimum width of extra large screens.": "아주 큰 화면의 최소 너비.",
  "Control the minimum width of extra small screens.": "아주 작은 화면의 최소 너비.",
  "Control the minimum width of large screens.": "큰 화면의 최소 너비.",
  "Control the minimum width of medium screens.": "중간 화면의 최소 너비.",
  "Control the minimum width of small screens.": "작은 화면의 최소 너비.",
  "Control the screen width of extra small screens.": "아주 작은 화면의 화면 너비.",
  "Control the screen width of large screens.": "큰 화면의 화면 너비.",
  "Control the screen width of medium screens.": "중간 화면의 화면 너비.",
  "Control the style of background color of content area when mouse hovers over it.": "내용 영역에 마우스를 올렸을 때의 바탕색.",
  "Current size of dot": "지금 점의 크기",
  "Default background color": "기본 바탕색",
  "Default color of progress bar": "진행 막대의 기본 색",
  "Default padding": "기본 안쪽 여백",
  "Default state color of success color text": "success 색 글자의 기본 상태 색",
  "Default text color": "기본 글자색",
  "Default text color for solid buttons.": "solid 버튼의 기본 글자색.",
  "Default text color for solid tag.": "solid 태그의 기본 글자색.",
  "Default text color for text buttons": "text 버튼의 기본 글자색",
  "Default text color for text buttons on active": "text 버튼을 누르고 있을 때의 기본 글자색",
  "Default text color for text buttons on hover": "text 버튼에 마우스를 올렸을 때의 기본 글자색",
  "Disabled color of preview operation icon": "못 쓰는 상태일 때 미리보기 조작 아이콘의 색",
  "Distance between text and edge, which should be a number between 0 and 1.": "글자와 가장자리 사이의 거리. 0 과 1 사이의 수여야 해요.",
  "End color of gradient": "그러데이션의 끝 색",
  "End padding of item": "항목의 끝쪽 안쪽 여백",
  "Font color of title": "제목의 글자색",
  "Font size of Avatar": "Avatar 의 글자 크기",
  "Font size of Avatar icon": "Avatar 아이콘의 글자 크기",
  "Font size of badge text": "badge 글자의 글자 크기",
  "Font size of button content": "버튼 내용의 글자 크기",
  "Font size of card header": "카드 머리의 글자 크기",
  "Font size of custom icon": "직접 넣은 아이콘의 글자 크기",
  "Font size of description": "설명의 글자 크기",
  "Font size of h1 tag.": "h1 태그의 글자 크기.",
  "Font size of h4 tag.": "h4 태그의 글자 크기.",
  "Font size of large Avatar": "큰 Avatar 의 글자 크기",
  "Font size of large Avatar icon": "큰 Avatar 아이콘의 글자 크기",
  "Font size of large button content": "큰 버튼 내용의 글자 크기",
  "Font size of large title": "큰 제목의 글자 크기",
  "Font size of small Avatar": "작은 Avatar 의 글자 크기",
  "Font size of small Avatar icon": "작은 Avatar 아이콘의 글자 크기",
  "Font size of small badge text": "작은 badge 글자의 글자 크기",
  "Font size of small button content": "작은 버튼 내용의 글자 크기",
  "Font size of small card header": "작은 카드 머리의 글자 크기",
  "Font size of small title": "작은 제목의 글자 크기",
  "Font size of table cell (large size by default)": "표 셀의 글자 크기 (기본은 큰 크기)",
  "Font size of table cell (middle size)": "표 셀의 글자 크기 (중간 크기)",
  "Font size of table cell (small size)": "표 셀의 글자 크기 (작은 크기)",
  "Font weight of badge text": "badge 글자의 글자 굵기",
  "Font weight of selected item": "고른 항목의 글자 굵기",
  "Font weight of text": "글자 굵기",
  "Form item margin bottom": "폼 항목의 아래쪽 바깥 여백",
  "Gap between icon and text": "아이콘과 글자 사이 간격",
  "Gutter of card tab": "카드 탭의 사이 간격",
  "Handle visible": "핸들 보임",
  "Height of Switch": "Switch 의 높이",
  "Height of badge": "badge 의 높이",
  "Height of card header": "카드 머리의 높이",
  "Height of card tab": "카드 탭의 높이",
  "Height of content area": "내용 영역의 높이",
  "Height of dropdown": "드롭다운의 높이",
  "Height of indicator": "표시자의 높이",
  "Height of large card tab": "큰 카드 탭의 높이",
  "Height of list": "목록의 높이",
  "Height of list item": "목록 항목의 높이",
  "Height of menu item active bar": "메뉴 항목 활성 막대의 높이",
  "Height of mini calendar content": "작은 달력 내용의 높이",
  "Height of popup": "팝업의 높이",
  "Height of rail": "레일의 높이",
  "Height of sider trigger": "사이드바 여닫이의 높이",
  "Height of sider trigger when collapse is 0": "접힘이 0 일 때 사이드바 여닫이의 높이",
  "Height of slider": "슬라이더의 높이",
  "Height of small Switch": "작은 Switch 의 높이",
  "Height of small badge": "작은 badge 의 높이",
  "Height of small card header": "작은 카드 머리의 높이",
  "Height of small card tab": "작은 카드 탭의 높이",
  "Height of title skeleton": "제목 스켈레톤의 높이",
  "Horizontal gutter of horizontal tab": "가로 탭의 좌우 사이 간격",
  "Horizontal margin of horizontal tab": "가로 탭의 좌우 바깥 여백",
  "Horizontal margin of horizontal tab item": "가로 탭 항목의 좌우 바깥 여백",
  "Horizontal margin of horizontal tab item (RTL)": "가로 탭 항목의 좌우 바깥 여백 (RTL)",
  "Horizontal margin of menu item": "메뉴 항목의 좌우 바깥 여백",
  "Horizontal margin of vertical Divider": "세로 Divider 의 좌우 바깥 여백",
  "Horizontal padding of Radio button": "Radio 버튼의 좌우 안쪽 여백",
  "Horizontal padding of a list item.": "목록 항목의 좌우 안쪽 여백.",
  "Horizontal padding of button": "버튼의 좌우 안쪽 여백",
  "Horizontal padding of footer": "바닥 영역의 좌우 안쪽 여백",
  "Horizontal padding of horizontal tab item": "가로 탭 항목의 좌우 안쪽 여백",
  "Horizontal padding of large button": "큰 버튼의 좌우 안쪽 여백",
  "Horizontal padding of large horizontal tab item": "큰 가로 탭 항목의 좌우 안쪽 여백",
  "Horizontal padding of link": "링크의 좌우 안쪽 여백",
  "Horizontal padding of small button": "작은 버튼의 좌우 안쪽 여백",
  "Horizontal padding of small horizontal tab item": "작은 가로 탭 항목의 좌우 안쪽 여백",
  "Horizontal padding of table cell (large size by default)": "표 셀의 좌우 안쪽 여백 (기본은 큰 크기)",
  "Horizontal padding of table cell (middle size)": "표 셀의 좌우 안쪽 여백 (중간 크기)",
  "Horizontal padding of table cell (small size)": "표 셀의 좌우 안쪽 여백 (작은 크기)",
  "Horizontal padding of text": "글자의 좌우 안쪽 여백",
  "Hover background color of next button in primary type": "primary 형태에서 다음 버튼에 마우스를 올렸을 때의 바탕색",
  "Hover color of danger menu item text": "danger 메뉴 항목 글자에 마우스를 올렸을 때의 색",
  "Hover color of handle": "핸들에 마우스를 올렸을 때의 색",
  "Hover color of horizontal menu item text": "가로 메뉴 항목 글자에 마우스를 올렸을 때의 색",
  "Hover color of menu item text": "메뉴 항목 글자에 마우스를 올렸을 때의 색",
  "Hover state of text color of information color.": "info 색 글자에 마우스를 올렸을 때의 상태.",
  "Icon size of button which only contains icon": "아이콘만 있는 버튼의 아이콘 크기",
  "Icon size of circular progress bar": "원형 진행 막대의 아이콘 크기",
  "Icon size of control button": "조작 버튼의 아이콘 크기",
  "Icon size of large button which only contains icon": "아이콘만 있는 큰 버튼의 아이콘 크기",
  "Icon size of small button which only contains icon": "아이콘만 있는 작은 버튼의 아이콘 크기",
  "Icon size with description": "설명이 있을 때의 아이콘 크기",
  "Inline layout form item margin bottom": "inline 배치 폼 항목의 아래쪽 바깥 여백",
  "Inline padding of multiple words badge": "여러 낱말 badge 의 좌우 안쪽 여백",
  "Label colon margin-inline-end": "라벨 콜론의 끝쪽 바깥 여백",
  "Label colon margin-inline-start": "라벨 콜론의 시작쪽 바깥 여백",
  "Label color": "라벨 색",
  "Label font size": "라벨 글자 크기",
  "Label height": "라벨 높이",
  "Large loading icon size": "큰 불러오는 중 아이콘 크기",
  "Large size": "큰 크기",
  "Large star size": "큰 별 크기",
  "Left margin of colon": "콜론의 왼쪽 바깥 여백",
  "Light background color of information color.": "info 색의 옅은 바탕색.",
  "Light background color of success color, used for Tag and Alert success state background color": "success 색의 옅은 바탕색. Tag 와 Alert 의 success 상태 바탕색에 써요",
  "Line color": "선 색",
  "Line height of h1 tag.": "h1 태그의 줄 높이.",
  "Line height of h2 tag.": "h2 태그의 줄 높이.",
  "Line height of h4 tag.": "h4 태그의 줄 높이.",
  "Line height of paragraph skeleton": "문단 스켈레톤의 줄 높이",
  "Line height of title": "제목의 줄 높이",
  "Line width": "선 굵기",
  "LineHeight of horizontal menu item": "가로 메뉴 항목의 줄 높이",
  "Loading icon size": "불러오는 중 아이콘 크기",
  "Margin bottom of meta": "메타 영역의 아래쪽 바깥 여백",
  "Margin bottom of tabs component": "탭 컴포넌트의 아래쪽 바깥 여백",
  "Margin of each item in card actions": "카드 동작 영역 각 항목의 바깥 여백",
  "Margin of extra area": "덧붙임 영역의 바깥 여백",
  "Margin of separator": "구분선의 바깥 여백",
  "Margin right of Radio button": "Radio 버튼의 오른쪽 바깥 여백",
  "Margin top of paragraph skeleton": "문단 스켈레톤의 위쪽 바깥 여백",
  "Margin top of title": "제목의 위쪽 바깥 여백",
  "Max width of nav content": "내비게이션 내용의 최대 너비",
  "Max width of tooltip": "툴팁의 최대 너비",
  "Maximum margin of content area": "내용 영역의 최대 바깥 여백",
  "Maximum margin of content area of small Switch": "작은 Switch 내용 영역의 최대 바깥 여백",
  "Min width of Popover title": "Popover 제목의 최소 너비",
  "Minimum margin of content area": "내용 영역의 최소 바깥 여백",
  "Minimum margin of content area of small Switch": "작은 Switch 내용 영역의 최소 바깥 여백",
  "Minimum width of Switch": "Switch 의 최소 너비",
  "Minimum width of small Switch": "작은 Switch 의 최소 너비",
  "Node size": "마디 크기",
  "Outline color of handle when active": "핸들이 활성일 때의 외곽선 색",
  "Overlapping of avatars in a group": "묶인 아바타들이 겹치는 정도",
  "Padding of Message": "Message 의 안쪽 여백",
  "Padding of Segmented container": "Segmented 상자의 안쪽 여백",
  "Padding of Switch": "Switch 의 안쪽 여백",
  "Padding of card body": "카드 본문의 안쪽 여백",
  "Padding of card head": "카드 머리의 안쪽 여백",
  "Padding of card tab": "카드 탭의 안쪽 여백",
  "Padding of content": "내용의 안쪽 여백",
  "Padding of content in borderless style": "테두리 없는 형태에서 내용의 안쪽 여백",
  "Padding of empty text": "빈 상태 글자의 안쪽 여백",
  "Padding of footer": "바닥 영역의 안쪽 여백",
  "Padding of item": "항목의 안쪽 여백",
  "Padding of large card tab": "큰 카드 탭의 안쪽 여백",
  "Padding of large content": "큰 내용의 안쪽 여백",
  "Padding of large header": "큰 머리 영역의 안쪽 여백",
  "Padding of large item": "큰 항목의 안쪽 여백",
  "Padding of menu item": "메뉴 항목의 안쪽 여백",
  "Padding of menu item (single column)": "메뉴 항목의 안쪽 여백 (한 줄일 때)",
  "Padding of small card body": "작은 카드 본문의 안쪽 여백",
  "Padding of small card head": "작은 카드 머리의 안쪽 여백",
  "Padding of small card tab": "작은 카드 탭의 안쪽 여백",
  "Padding of small content": "작은 내용의 안쪽 여백",
  "Padding of small header": "작은 머리 영역의 안쪽 여백",
  "Padding of small item": "작은 항목의 안쪽 여백",
  "Padding with description": "설명이 있을 때의 안쪽 여백",
  "Radio size": "Radio 크기",
  "Radius of menu item": "메뉴 항목의 모서리",
  "Radius of sub-menu item": "하위 메뉴 항목의 모서리",
  "Required mark color": "필수 표시의 색",
  "Right margin of avatar": "아바타의 오른쪽 바깥 여백",
  "Right margin of colon": "콜론의 오른쪽 바깥 여백",
  "Scale of star when hover": "별에 마우스를 올렸을 때의 확대 비율",
  "Shadow of Switch handle": "Switch 핸들의 그림자",
  "Shadow of danger button": "danger 버튼의 그림자",
  "Shadow of default button": "default 버튼의 그림자",
  "Shadow of primary button": "primary 버튼의 그림자",
  "Size of Avatar": "Avatar 의 크기",
  "Size of Pagination item": "Pagination 항목의 크기",
  "Size of Radio dot": "Radio 점의 크기",
  "Size of Switch handle": "Switch 핸들의 크기",
  "Size of arrows": "화살표의 크기",
  "Size of custom icon container": "직접 넣은 아이콘 상자의 크기",
  "Size of dot badge": "점 badge 의 크기",
  "Size of handle": "핸들의 크기",
  "Size of handle when hover": "핸들에 마우스를 올렸을 때의 크기",
  "Size of icon container": "아이콘 상자의 크기",
  "Size of icon when collapsed": "접혔을 때 아이콘의 크기",
  "Size of large Avatar": "큰 Avatar 의 크기",
  "Size of large Pagination item": "큰 Pagination 항목의 크기",
  "Size of list items in card type (affects both picture-card and picture-circle)": "카드 형태 목록 항목의 크기 (picture-card 와 picture-circle 둘 다에 걸려요)",
  "Size of preview operation icon": "미리보기 조작 아이콘의 크기",
  "Size of resize handle": "크기 조절 핸들의 크기",
  "Size of small Avatar": "작은 Avatar 의 크기",
  "Size of small Pagination item": "작은 Pagination 항목의 크기",
  "Size of small Switch handle": "작은 Switch 핸들의 크기",
  "Size of small steps icon": "작은 steps 아이콘의 크기",
  "Size of status badge": "상태 badge 의 크기",
  "Small loading icon size": "작은 불러오는 중 아이콘 크기",
  "Small star size": "작은 별 크기",
  "Solid background color active state, currently only used in the active effect of the default solid button.": "solid 바탕색을 누르고 있을 때. 지금은 default solid 버튼에만 써요.",
  "Solid background color hover state, currently only used in the hover effect of the default solid button.": "solid 바탕색에 마우스를 올렸을 때. 지금은 default solid 버튼에만 써요.",
  "Spacing between avatars in a group": "묶인 아바타들 사이의 간격",
  "Spacing between icon and text": "아이콘과 글자 사이의 간격",
  "Split border color of table header": "표 머리를 나누는 선 색",
  "Star background color": "별의 바탕색",
  "Star color": "별의 색",
  "Star size": "별의 크기",
  "Start color of gradient": "그러데이션의 시작 색",
  "Subtitle font size": "부제목의 글자 크기",
  "Text color of Breadcrumb item": "Breadcrumb 항목의 글자색",
  "Text color of active Pagination item": "활성 Pagination 항목의 글자색",
  "Text color of active Pagination item hover": "활성 Pagination 항목에 마우스를 올렸을 때의 글자색",
  "Text color of active tab": "활성 탭의 글자색",
  "Text color of circular progress bar": "원형 진행 막대의 글자색",
  "Text color of content": "내용의 글자색",
  "Text color of danger button": "danger 버튼의 글자색",
  "Text color of default button": "default 버튼의 글자색",
  "Text color of default button when active": "default 버튼을 누르고 있을 때의 글자색",
  "Text color of default button when hover": "default 버튼에 마우스를 올렸을 때의 글자색",
  "Text color of default ghost button": "default ghost 버튼의 글자색",
  "Text color of disabled active Pagination item": "못 쓰는 활성 Pagination 항목의 글자색",
  "Text color of header": "머리 영역의 글자색",
  "Text color of hover tab": "마우스를 올린 탭의 글자색",
  "Text color of item": "항목의 글자색",
  "Text color of item when hover": "항목에 마우스를 올렸을 때의 글자색",
  "Text color of item when selected": "항목을 골랐을 때의 글자색",
  "Text color of label": "라벨의 글자색",
  "Text color of link": "링크의 글자색",
  "Text color of primary button": "primary 버튼의 글자색",
  "Text color of selected directory node": "고른 디렉터리 마디의 글자색",
  "Text color of selected tab": "고른 탭의 글자색",
  "Text color of tab": "탭의 글자색",
  "Text color of the last item": "마지막 항목의 글자색",
  "Text color of title": "제목의 글자색",
  "Text size of circular progress bar": "원형 진행 막대의 글자 크기",
  "The active state background color of the error state.": "error 상태를 누르고 있을 때의 바탕색.",
  "The active state of the error color.": "error 색을 누르고 있을 때.",
  "The active state of the text in the error color.": "error 색 글자를 누르고 있을 때.",
  "The background color of the overlay menu in dark mode.": "다크 모드에서 덮는 메뉴의 바탕색.",
  "The border color of the error state.": "error 상태의 선 색.",
  "The border color of the warning state.": "warning 상태의 선 색.",
  "The hover state of the stroke color under the main color gradient, which will be used when the stroke Hover of components such as Slider and Button.": "주색 계조 중 선 색에 마우스를 올렸을 때. Slider · Button 따위의 선 hover 에 써요.",
  "The hover state of the text in the error color.": "error 색 글자에 마우스를 올렸을 때.",
  "This color is used to draw the user's strong attention to the background color, and is currently only used in the background color of Tooltip.": "사용자의 눈길을 강하게 끄는 바탕색. 지금은 Tooltip 의 바탕색에만 써요.",
  "Top of Pagination size changer": "Pagination 크기 바꾸기의 위쪽 위치",
  "Top of custom icon": "직접 넣은 아이콘의 위쪽 위치",
  "Top of icon": "아이콘의 위쪽 위치",
  "Tour popup z-index": "Tour 팝업의 z-index",
  "Used to derive the base variable of the background color gradient. In v5, we added a layer of background color derivation algorithm to produce map token of background color. But PLEASE DO NOT USE this Seed Token directly in the code!": "바탕색 계조를 파생시키는 기준 변수. v5 에서 바탕색 map 토큰을 만드는 파생 알고리즘을 한 겹 더 두었어요. 이 Seed 토큰을 코드에서 직접 쓰지는 마세요!",
  "Vertical layout label margin": "세로 배치에서 라벨의 바깥 여백",
  "Vertical layout label padding": "세로 배치에서 라벨의 안쪽 여백",
  "Vertical margin of vertical tab item": "세로 탭 항목의 위아래 바깥 여백",
  "Vertical padding of a list item.": "목록 항목의 위아래 안쪽 여백.",
  "Vertical padding of dropdown": "드롭다운의 위아래 안쪽 여백",
  "Vertical padding of footer": "바닥 영역의 위아래 안쪽 여백",
  "Vertical padding of link": "링크의 위아래 안쪽 여백",
  "Vertical padding of list item": "목록 항목의 위아래 안쪽 여백",
  "Vertical padding of table cell": "표 셀의 위아래 안쪽 여백",
  "Vertical padding of table cell (middle size)": "표 셀의 위아래 안쪽 여백 (중간 크기)",
  "Vertical padding of table cell (small size)": "표 셀의 위아래 안쪽 여백 (작은 크기)",
  "Vertical padding of vertical tab item": "세로 탭 항목의 위아래 안쪽 여백",
  "Width of Cascader": "Cascader 의 너비",
  "Width of Notification": "Notification 의 너비",
  "Width of active indicator": "활성 표시자의 너비",
  "Width of content": "내용의 너비",
  "Width of control button": "조작 버튼의 너비",
  "Width of indicator": "표시자의 너비",
  "Width of input": "입력칸의 너비",
  "Width of item": "항목의 너비",
  "Width of large list": "큰 목록의 너비",
  "Width of list": "목록의 너비",
  "Width of menu item active bar": "메뉴 항목 활성 막대의 너비",
  "Width of month select": "월 고르기의 너비",
  "Width of popup menu": "팝업 메뉴의 너비",
  "Width of selection column": "선택 열의 너비",
  "Width of sider trigger when collapse is 0": "접힘이 0 일 때 사이드바 여닫이의 너비",
  "Width of year select": "연 고르기의 너비",
  "Width when collapsed": "접혔을 때의 너비",
  "XS component height": "아주 작은 컴포넌트 높이",
  "arrows offset to Carousel edge": "Carousel 가장자리에서 화살표까지의 거리",
  "dot offset to Carousel edge": "Carousel 가장자리에서 점까지의 거리",
  "font-size of group title": "그룹 제목의 글자 크기",
  "gap between indicator": "표시자 사이의 간격",
  "line-height of group title": "그룹 제목의 줄 높이",
  "margin-block of menu item": "메뉴 항목의 위아래 바깥 여백",
  "padding-inline of menu item": "메뉴 항목의 좌우 안쪽 여백",
  "z-index of Message": "Message 의 z-index",
  "z-index of Notification": "Notification 의 z-index",
  "z-index of Popconfirm": "Popconfirm 의 z-index",
  "z-index of Popover": "Popover 의 z-index",
  "z-index of badge": "badge 의 z-index",
  "z-index of drawer": "drawer 의 z-index",
  "z-index of dropdown menu": "드롭다운 메뉴의 z-index",
  "z-index of popup menu": "팝업 메뉴의 z-index",
  "z-index of preview popup": "미리보기 팝업의 z-index",
  "z-index of tooltip": "툴팁의 z-index",
};
